### ISSUE TITLE
print_rel_notes' workspace snippet is poorly wrapped when viewed from github

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_pkg#103]
Looking at the Bazel Federation's [release notes](https://github.com/bazelbuild/bazel-federation/releases), if you copy and paste the workspace snippet, you get a spurious linebreak in the url. Can we do anything to avoid that?

**Comment by brandjon** [comment]
Since this doesn't happen in the rules_python release, I suspect this was a one-off error from manual relnotes editing.

**Comment by aiuto** [comment]
I think this was a function of my own sloppy copy/paste.
