### ISSUE TITLE
Deterministic RPMs through modifying Build host and Build time via LD_PRELOAD

### ISSUE THREAD

**Issue by mmikitka** [bazelbuild/rules_pkg#105]
rpmbuild does not produce deterministic builds because the following metadata fields (see `rpm -qip`) cannot be controlled via flags:
1. "Build host"
2. "Build time"

It looks like a common approach to addressing these shortcomings is overriding `int gethostname(char* name, size_t len)` and `time_t time(time_t* timer)` in a custom library, and referencing this library in `LD_PRELOAD` when `rpmbuild` is invoked.

PR with this solution is forthcoming

**Comment by aiuto** [comment]
Let's try to figure out how to do this without a preload library.  Have you tried defining _buildhost in the .spec file?  That is half the battle there.

**Comment by mmikitka** [comment]
@aiuto You're right - I was not aware of `_buildhost` and `SOURCE_DATE_EPOCH`, which can be used to modify the build host and build time, respectively. I'll cut another issue and PR to fix this without ld_preload.
