### ISSUE TITLE
Unable to get pkg_rpm to work

### ISSUE THREAD

**Issue by mhae** [bazelbuild/rules_pkg#110]
I'm trying to use pkg_rpm but none of the files specified in the data property are being copied to the rpm build structure.
Version info:
```
bazel 0.29.1
http_archive(
   name = "rules_pkg",
   url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.4/rules_pkg-0.2.4.tar.gz",
   sha256 = "4ba8f4ab0ff85f2484287ab06c0d871dcb31cc54d439457d28fd4ae14b18450a",
)
```

Build
```
pkg_rpm(
    name = "Foo",
    architecture = "x86_64",
    spec_file = "foo.spec",
    version = "0",
    release = "1",
    data = [
        "README",
    ]
)
```

foo.spec
```
Summary: Foo
Name: Foo
Version: 0
Release: 1
License: (C) Copyright 2019 Foo
Vendor: Foo
Packager: Foo <foo@bar.com>

%description
Foo

%files
/README
```

The README file is in the same directory as the BUILD and spec file.

If been looking through the make_rpm.py script and I don't see how the source files are being copied to the RPM structure under /tmp:
```
with Tempdir() as dirname:
      self.SetupWorkdir(spec_file, original_dir)
      status = self.CallRpmBuild(dirname)
      self.SaveResult(out_file)
```
Shouldn't all the files in ```data`` being copied to the rpm structure under ```dirname```?

Or is there something else I need to do in ```data``` or ```%files```?

Any pointers are appreciated...

**Comment by aiuto** [comment]
From looking at other bugs today, it seems like your .spec file is missing an %install section.
See #86 for more details and try with the code at head.

**Comment by aiuto** [comment]
Closing on timeout. If this is still a problem please ask to re-open.
