### ISSUE TITLE
Reproducible RPM build host and build time

### ISSUE THREAD

**Issue by mmikitka** [bazelbuild/rules_pkg#112]
If you want to control the RPM `Build host` metadata, use `_buildhost` in your RPM spec

If you want to control the `Build time` metadata, the `SOURCE_DATE_EPOCH` environment variable must be declared within the context of running rpmbuild.

PR is forthcoming with support for `SOURCE_DATE_EPOCH`

For context, see:
* https://reproducible-builds.org/docs/source-date-epoch/
* https://wiki.yoctoproject.org/wiki/Reproducible_Builds

Related to https://github.com/bazelbuild/rules_pkg/issues/105

**Comment by aiuto** [comment]
Closing.  The build time part is done.  The rest should be addressed in #53

**Comment by wxlg1117** [comment]
> 
> 
> If you want to control the RPM `Build host` metadata, use `_buildhost` in your RPM spec
> 

how to do ? please show a sample .spec ,thank you very much!
