### ISSUE TITLE
Prepend prefix "./" to all files added to control.tar by make_deb

### ISSUE THREAD

**Issue by andreas-0815-qwertz** [bazelbuild/rules_pkg#116]
dpkg packs files in control.tar using a "./".  I have no authoritative source for this, but the [Debian Administrator's Handbook](https://debian-handbook.info/browse/stable/packaging-system.html) for instance confirms this.

There are tools out there, relying on this convention; in my case it is the ancient version 0.1.8 of [opkg](https://github.com/shr-project/opkg).

**Comment by aiuto** [comment]
Fixed in #121
