### ISSUE TITLE
Feature: support shlibs in pkg_deb

### ISSUE THREAD

**Issue by alisafari1998** [bazelbuild/rules_pkg#134]
Whenever a Debian package contains a shared library, it is required to have a `shlibs` file in `DEBIAN` directory (next to the `control` file).
Currently, running `lintain` (tool for checking correctness of Debian packages) on bazel-generated  Debian packages (containing a shared library) will result in the following error:
```
E: libmylib1: no-shlibs-control-file usr/lib/libmylib.so.1.1
```
Related document is available at https://lintian.debian.org/tags/no-shlibs-control-file.html

**Comment by aiuto** [comment]
Closing issues that no one is likely to work on for any forseable future
