### ISSUE TITLE
example package name does not follow Debian naming conventions.

### ISSUE THREAD

**Issue by ghost** [bazelbuild/rules_pkg#143]
This line appears to be incorrect

https://github.com/bazelbuild/rules_pkg/blob/master/pkg/pkg.bzl

`line 375  out_deb = "%s_%s_%s.deb" % (package, version, architecture)
`
The the name is not following the correct syntax.
`<foo>_<VersionNumber>-<DebianRevisionNumber>_<DebianArchitecture>.deb 
`
(https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html)

foo_VVV-RRR_AAA.deb (where VVV, RRR and AAA are the version, revision and architecture of the package in question, respectively)
Package names (both source and binary, see Package) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.). They must be at least two characters long and must start with an alphanumeric character.
Regular expressions are not currently supported. however some simple checks should be possible for example:

```
if '_' not in name:
   for x in name.elems():
     if x.isupper():
          fail("Uppercase characters are not allowed in package names", "name")
     elif x in "+-.":
            continue
     elif not x.alnum():
          fail("Only lowercase characters and numbers are allowed in package names", "name")
     else
        fail("_ is not allowed in package names", "name")
               

```

**Comment by aiuto** [comment]
It is not really inconsistent.  version is just a string. If the user wants a conformant name, they can specify a version for the form version-revision, and you'll get a result that is fine.
