### ISSUE TITLE
Document pkg_tar's "files" argument

### ISSUE THREAD

**Issue by jatcwang** [bazelbuild/rules_pkg#152]
Documentation URL: https://docs.bazel.build/versions/master/be/pkg.html

The `files` argument is a dict that allows the user to map multiple files to different locations. This avoid multiple pkg_tar calls when you want to put files in different locations

Code: https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/pkg.bzl#L253
Original issue adding the feature: https://github.com/bazelbuild/bazel/issues/3317

Happy to submit a patch but I'm not sure where the doc is hosted

**Comment by aiuto** [comment]
I'm prioritizing this as P3 but wontfix. It is clearly undocumented, but the better solution is to find a replacement for it. I hope with the work on pkgfilegroup
