### ISSUE TITLE
Fix and document pkg_tar() runfiles support.

### ISSUE THREAD

**Issue by chin33z** [bazelbuild/rules_pkg#153]
When build with --dynamic_mode=fully, pkg_tar() only tars the "files" into the tarball. It does not include the shared library(located in the runfile tree) it needs. It would be nice if pkg_tar packing all the resources it needs. Thanks.

**Comment by aiuto** [comment]
I have been doing a sprint on supporting pkg_files* in pkg_tar.  I think I have a design I like. I wanted to stick it out here for comment.  

We start with some requirements
- `*_binary `rules must not change in any way
- Distributions might want to place a binary in a different relative path from the root than the package path in your workspace.  For example.   `//my/project/src:footool` might be installed to /usr/bin/footool
- Distributions might want data and/or binary runfiles in specific places
  - data files might be best in /usr/share/footool/...
  - binary runfiles (.so or .py) might be in /usr/bin/footool.runfiles/... or maybe /usr/lib/footool/runfiles/...
- The policy of where files might be mapped belongs to the packager, so we want to specify it somewhere else than in the `*_binary` rule
- A single `pkg_tar` (or `pkg_*`) target might bundle multiple binaries each with different choices for relocating runfiles. So, we want to declare data and runfile remapping outside the `pkg_tar` rule to avoid clutter.

So, the idea is you would do this
```
cc_binary(name="foo", ..., data=[":baz"])

pkg_files(
   name='foo_bin',
   srcs = [':foo'],
   strip_prefix=strip_prefix.from_root(),   # removes package path from ultimate path of foo
   prefix = '/usr/bin'                                     # makes it appear as /usr/bin/foo
   runfiles_prefix = '/usr/share/foo',           # makes runfiles appear as a tree under /usr/share/foo
)

pkg_zip(name = 'foozip', srcs=['foo_bin'])
```
What this is missing though, is the way to know that some runfiles are noarch and some are not. That is, we don't have a good way to automatically know what should be in /usr/share/foo vs. /usr/lib/foo.  I started a separate discussion thread on bazel-discuss to talk about that.

Extended example of the progress so far: https://github.com/aiuto/rules_pkg/tree/rich/examples/rich_structure

**Comment by limdor** [comment]
> I have been doing a sprint on supporting pkg_files* in pkg_tar. I think I have a design I like. I wanted to stick it out here for comment.

@aiuto could you post it here once you have some first implementation even if it is not merged? I would be curious on trying it out. I'm trying to understand how should be done when the run file is a dependency deep in the tree. In my case I was using it to pack dlls into the tar.gz file in windows.
https://github.com/limdor/quoniam/blob/457cc363eab642362754c9c64715231ee3e05a9e/src/BUILD#L103

**Comment by aiuto** [comment]
On Sun, May 30, 2021 at 6:19 AM Xavier Bonaventura ***@***.***>
wrote:

> I have been doing a sprint on supporting pkg_files* in pkg_tar. I think I
> have a design I like. I wanted to stick it out here for comment.
>
> @aiuto <https://github.com/aiuto> could you post it here once you have
> some first implementation even if it is not merged? I would be curious on
> trying it out. I'm trying to understand how should be done when the run
> file is a dependency deep in the tree. In my case I was using it to pack
> dlls into the tar.gz file in windows.
>
> https://github.com/limdor/quoniam/blob/457cc363eab642362754c9c64715231ee3e05a9e/src/BUILD#L103
>

I don't have any design for the best way to do runfiles at this time.
Right now I am trying to get all the pkg_files rules working.
Take a look at https://github.com/aiuto/rules_pkg/tree/rich, especially
https://github.com/aiuto/rules_pkg/tree/rich/examples/rich_structure

You can help me by coming up with an idealized outcome for your use case.
- should DLLs reside next to the .exe file?
- if not, must they go in some other specific place or could it be anywhere
that the .exe knows about
- should they go to some place like %USERPROFILEDIR%/AppData/...
- if there was a pkg_msi rule, should it do something different with DLLs.


Do you build for multiple platforms?

**Comment by limdor** [comment]
In my case (in the first iteration) I need to create a zip file that apart from the executable should contain:
- DLLs that should reside next to the .exe file
- Shaders used by the rendering engine that should also go next to the executable (ideally inside a shaders folder). These would see them declared in a cc_library (the renderer) as data files.

Regarding multi-platform currently I only build for Windows, but at some point the project was building with Linux and MacOS. At some point I want to have it back, more for the sake of having it than nothing else. In the end the project is the result of my PhD and I just keep it as a playground with a realistic use case.

Abou msi, at some point I was using Inno Setup to create the installer for windows but I did not spend the time to integrate it in Bazel. The goal would be to be able to create a installer for Windows using Bazel. With Inno Setup, MSI, or anything equivalent.

**Comment by aiuto** [comment]
On Wed, Jun 9, 2021 at 3:48 PM Xavier Bonaventura ***@***.***>
wrote:

> In my case (in the first iteration) I need to create a zip file that apart
> from the executable should contain:
>
>    - DLLs that should reside next to the .exe file
>    - Shaders used by the rendering engine that should also go next to the
>    executable (ideally inside a shaders folder). These would see them declared
>    in a cc_library (the renderer) as data files.
>
> Cool. That's a good starting point for a discussion. What you ask for is
probably reasonable for a lie of people. In any case, it is certainly
better than them being under  foo.exe.runfiles/some/long/path.


For your case, does your executable directly depend on the DLLs and
shaders, or are they transitively included data from other places?  Or a
mix?

**Comment by limdor** [comment]
> For your case, does your executable directly depend on the DLLs and
shaders, or are they transitively included data from other places?  Or a
mix?

In general they are all transitive dependencies. Currently the shaders I add them at the end target but the logic would be that the target that needs them declare them as a runtime dependency.
The problem here is that I do not know even in an ideal world how it should look like. When declaring the runtime dependency using the attribute `data` the problem is that you say what data should be available but you are not saying anything about where will be located. I didn't dig deeper but for what I understood there is a way to know the location of the `data` that is related to the root of the workspace.
The interesting part is what if you want this data in a different location, like what we are discussing with the pkg rules. The problem that I see here is where it would be declared. You could have a remap that says each folder where should be relocated but the most logical would be that this information is together with the library that uses them. Something like `data_location` as an attribute of the `cc_library`. Of course this supposing that could be done has the problem that I guess it would break the Bazel idea, and you could not know if conflicts with another file until you package it.

**Comment by aiuto** [comment]
I think an important part is to be able to build a layout that follows the
install pattern of the target is. The bazel layout is not that.  I want to
explore the idea of making a runfiles prebuilt remapping that puts shared
libraries under one path and data under another.

And, we have a problem with the runfiles library. You normally have to use
it to load data under bazel test. But then you lock in a bad layout.

In any case, this is an upcoming focus.

**Comment by thesayyn** [comment]
Hey @aiuto. 

I have a solution for this which I implement for https://github.com/thesayyn/rules_container. and it works perfectly fine and lays out the files the same exact way bazel does. 

See: https://github.com/thesayyn/rules_container/blob/main/language/runfiles.bzl

I would like to adapt it to `include_runfiles`.  It is language-agnostic and can handle anything out there.

See: https://github.com/thesayyn/rules_container/blob/main/example/js/BUILD.bazel for `nodejs_binary` 
Also see: https://github.com/thesayyn/rules_container/blob/main/example/py/BUILD.bazel for `py_binary`

I would be more than happy to get this landed on pkg_tar. 

WDYT?

**Comment by aiuto** [comment]
Thanks for the offer, but I don't think that doing it the way Bazel does is actually what people need. That is fine if bazel is going to run the object, but most packaging is about installing, so we need some capability to move things in the right way, as in @limdor\'s use case about moving DLLs to next to exe's.

If your expand_runfiles rule could do the path stripping and rebasing as in pkg_files, that might make a good start. But maybe then, it is just an option to pkg_files?

**Comment by pauldraper** [comment]
@thesayyn's solution is exactly what I was looking for: translating runfiles verbatim to PackageFilegroupInfo.

This is AWESOME.

It's suitable for a /opt-style install. Here's an archive. Unpack it and run it.

**Comment by thesayyn** [comment]
I'd like to upstream it with proper test.

**Comment by pauldraper** [comment]
There is `include_runfiles` support. That *almosts* works, but unfortunately has some issues putting the files in the paths expect by the runfiles tree.

**Comment by aiuto** [comment]
Sorry I'm a little slow on the response to this. I have a bunch of PRs out
for review that also get us closer to better runfiles support.  My strong
preference is that any change happens in pkg_files rather than distinctly
in build_tar, so that it is shared with zip. I've been looking at some
things people are doing with runfiles and an recurring idiom I have seen is

```
pkg_tar(..., include_runfiles=true, links={foo: "foo.runfiles/my/foo"} )
```
where the intent is that there becomes a top level symlink to actual binary
somewhere in the tree. This allows the executable to find it's runfiles
based on relative path to itself.  I'm trying to figure out a nice syntax
for that can provide better packaging. One of the "better" things would be
to be able to put the runfiles at any spot in the final package, without
having ".runfiles" as part of the name.  That is just plain ugly.

**Comment by pauldraper** [comment]
I just can't seem to get `include_runfiles` to work.

Like....there is no `foo.runfiles` tree, and there is an `external/` directory that shouldn't be the in the runfile tree.

> be able to put the runfiles at any spot in the final package

I think some rules (Python?) might depend on that particular naming of the runfiles dir.

> That is just plain ugly.

I guess. Whoever came up with `$0.runfiles` liked it I'm sure.

---

I created `pkg_runfiles` and `pkg_executable` rules: https://gist.github.com/pauldraper/7bc811ffbef6d3f3d4a4bb01afa9808f

**Comment by aiuto** [comment]
Oh yes. I don't think runfiles works correctly at head at all. I have a few
PRs waiting for an approve which will help.

**Comment by aiuto** [comment]
Yes.   The last PR which would have enabled it has a serious bug.  I need
to fix that

**Comment by ashuels** [comment]
> 

@njlr Thanks for the solution! I am trying to implement this workaround now but it doesn't appear to be keeing the ___init__.py files that Bazel auto includes when using `py_binary`. 

Is there a reason pkg_tar excludes the __init__.py files?

**Comment by njlr** [comment]
> > 
> 
> @njlr Thanks for the solution! I am trying to implement this workaround now but it doesn't appear to be keeing the `__init__.py` files that Bazel auto includes when using `py_binary`.
> 
> Is there a reason pkg_tar excludes the `__init__.py` files?

In my case I was including the `__init__.py` files explicitly via a `glob` and this works

**Comment by thesayyn** [comment]
here @f0rmiga
