### ISSUE TITLE
Don't force pkg_tar to use Python 2

### ISSUE THREAD

**Issue by davschne** [bazelbuild/rules_pkg#157]
I'm having trouble understanding why `build_tar.py` [is specified to use Python 2](https://github.com/bazelbuild/rules_pkg/blob/1c799ba44baf2a79bd58580bed41ef414480c76f/pkg/BUILD#L40). In my project, which uses `pkg_tar`, this is causing problems, because we use a toolchain that only includes Python 3. I know there are some workarounds, but I wonder if it's possible to simply remove the `python_version = "PY2"` attribute when creating the `build_tar` target.

**Comment by aiuto** [comment]
It may be historical accident.  I converted almost everything else, but still left behind the ability to use python2 for make_deb.py.  I don't see a need to support python2 forever.

**Comment by aiuto** [comment]
fixed in #158
