### ISSUE TITLE
Error in getListField

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_pkg#16]
Just trying out these rules and as trying to follow the readme as closely as possible getting the following error on running `bazel run //:update_deb_packages`

```
2018/08/21 15:37:07 Error in getListField, command: &{/home/markus/go/bin/buildozer [buildozer print tags -:packages] []  0xc42014c2d0  <nil> [] <nil> 0xc4201683c0 exit status 2 <nil> <nil> true [0xc42016e000 0xc42016e028 0xc42016e030] [0xc42016e000 0xc42016e028 0xc42016e030] [0xc42016e008 0xc42016e020] [0x60dac0 0x60dbc0] 0xc42018a000 <nil>}
2018/08/21 15:37:07 exit status 2
```

Investigating now, but maybe the error could already be a bit more descriptive.

**Comment by MarkusTeufelberger** [comment]
Install buildozer and yes, I agree.

Ideally, the tool would go-import buildozer directly, but since it is one of the first programs I wrote in golang, I didn't want to go down that rabbit hole immediately.

**Comment by Globegitter** [comment]
Ahh, I think I found the issue - it is commented out lines in my `debs = []` and commented out `container_image` rules.

The error when I did not have buildozer installed was actually quite descriptive :)

**Comment by aiuto** [comment]
Closing as obsolete because no one is working on the debrules part of this repository.

**Comment by aisbaa** [comment]
I've hit the same issue, @Globegitter did you find the fix/workaround for this?
