### ISSUE TITLE
Document experimental packaging rules

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#174]
The rules in pkg/experimental should be documented somewhat.  We (I) need to provide things like:

- An introduction
- General usage
- Thoughts on where things are going
- Stardoc emission

**Comment by nacl** [comment]
Important things to discuss:

- How implicit package directory structures are created
- How package builders may "de-relevatize" paths

**Comment by aiuto** [comment]
Also
- where to assign modes, owners, and groups to files
- symlinks

**Comment by aiuto** [comment]
Obsolete. There is no more experimental.
