### ISSUE TITLE
Tests requiring `rpmbuild(8)` cannot be run in CI

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#183]
The bazelci images for macOS and Ubuntu images in `bazelci` naturally do not have `rpmbuild(8)` on them, so any tests that run `rpmbuild` on them will fail.

I did a little digging into the docker images, and it looks like the provided centos7 image [doesn't have rpmbuild either](https://github.com/bazelbuild/continuous-integration/blob/e93e893071f90a066b2182c58ef4460ae6eb75eb/buildkite/docker/centos7/Dockerfile).

Fixing this will probably require modifying the CI setup, unless the centos7 image somehow has `rpmbuild(8)` in some way that is not apparent from examining the base docker image and the deplist of the installed packages in the image's dockerfile.

**Comment by nacl** [comment]
Waaaah the CentOS 7 image really doesn't have `rpmbuild(8)`: https://buildkite.com/bazel/rules-pkg/builds/51#1bab6d56-e677-481c-9600-bc21b8a3086d

**Comment by aiuto** [comment]
Rather than taking the test out of common, just unfurl a separate section for centos.
Or, split common up into   dep_tests, rpm_tests, tar_tests, ... and invoke those in each os block.

**Comment by aiuto** [comment]
Never mind that last comment. I didn't quite get the severity of the problem.

**Comment by aiuto** [comment]
Getting closer. The centos images now have rpmbuild. They just need a newer of version.

**Comment by aiuto** [comment]
This was fixed in 39b75b517b44f3a61272bb02b77867f49f95f5bc
