### ISSUE TITLE
Move experimental/pkg_filegroup up a level?

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#187]
@nacl  What do you think about moving the provider up to the top level?
That will allow us to start trying to use it for pkg_tar ans pkg_zip as well?

**Comment by nacl** [comment]
I'm hesitant to do this right now, given that some of the kinks are still being worked out.  There will also be a nontrivial interface change to pkg_zip and pkg_tar.

Regardless, there's nothing stopping development of a tar/zip rule in pkg/experimental/, so I'd like to defer this for a bit longer.
