### ISSUE TITLE
Clarify intentions for this repo

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/rules_pkg#2]
Hi Markus! Thanks for sending the initial PR for this repo. Small request—the README says "Currently these rules are focused on retrieving already built packages from repositories, not creating them as artifacts." ...

Can you expand a bit to clarify that we do, in fact, intend for this repo to expand and replace those built-in rules? (And an explanation about why that's a good thing to do?) Thanks!

**Comment by MarkusTeufelberger** [comment]
Sure, I just didn't want to assume ownership and direction over the whole repo right from the get-go. :-)
