### ISSUE TITLE
Confused about how to use `update_deb_packages` in another Bazel repository

### ISSUE THREAD

**Issue by adragomir** [bazelbuild/rules_pkg#20]
The problem seems to be that even when adding to WORKSPACE and BUILD references, running the `update_deb_packages` throws errors about 

    no such package '@org_golang_x_crypto//openpgp': The repository could not be resolved and referenced by '@rules_pkg//tools/update_deb_packages/src:update_deb_packages'

Why is that ? Should we be able to use this repository only by adding the documented things to WORKSPACE and BUILD ? Is this an issue ?

**Comment by aiuto** [comment]
Closing because no one is maintaining the deb_packages part any more.
