### ISSUE TITLE
strip_prefix=.  does not obey folder boundaries

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#207]
Given packages   //tests and //tests_extra, with targets
tests:a == ["foo/bar"] and tests_extra == ["foo/bar"] 
we would expect the content to be
```
./foo/bar       # //tests is correctly stripped
./tests_extra/foo/bar"  

But for the second file we get   "./_extra/foo/bar".

**Comment by dannysullivan** [comment]
@aiuto I just reproduced this and am planning on fixing it - please let me know if that's okay with you, or if there's anything else I should know here.

**Comment by aiuto** [comment]
I'm always happy if other people fix bugs.
