### ISSUE TITLE
Determine how package attributes/files might be templated using package metadata

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#210]
It was pointed out in the [review for #173](https://github.com/bazelbuild/rules_pkg/pull/179#discussion_r438339042) that we may want to expand various template attributes (e.g. the version) to other parts of the RPM spec file, such as the `%description`.

This raises another larger point: what attributes of packages should be template-able?  In many cases, it might make sense to subject all of them to template substitution, for example, some filesystem paths are annotated with versions, like those in `/usr/share/doc` in CentOS.

Another important part of this is figuring out the templates' syntax and how they're to be processed in a cross-platform manner.

**Comment by aiuto** [comment]
Yes. The more the merrier.  The idea in #198 allows us to bring a dict of string->string mappings into any of the rules so that we can expand it in any way we need. Any rpm spec template is a possibility

**Comment by aiuto** [comment]
This is getting old and not specifically actionable. Closing to clean out the backlog.
