### ISSUE TITLE
Creating and examining tar files on Windows seems to loose the directory entries.

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#213]
While working on #211 I noticed that the directory elements to not appear.
This might be because Python tarfile read on windows might not be reporting them,
or tarfile write might not be creating them. 

It's not like there is a lot of demand for producing debian packages from windows
at this time, so I'm just filing this for now to come back and resolve later.

**Comment by nkoroste** [comment]
I think the same is true on Linux and Mac
