### ISSUE TITLE
Allow more dynamism in pkg_tar arguments

### ISSUE THREAD

**Issue by guoshimin** [bazelbuild/rules_pkg#226]
Currently, arguments like `symlinks` and `empty_dirs` need to be fixed at loading time. It would be useful to have these provided at analysis time (by exposing the implementation function to other starlark rules) or at runtime (by providing these arguments as files.)

**Comment by aiuto** [comment]
Can you clarify the request with an example?

**Comment by guoshimin** [comment]
- exposing the implementation function to other starlark rules: For example, in rules_docker, the [implementation](https://github.com/bazelbuild/rules_docker/blob/9bfcd7dbf0294ed9d11a99da6363fc28df904502/container/layer.bzl#L177-L192) of the `container_layer` rule has a signature where, in addition to `ctx`, there is also an optional parameter for each attribute of the rule. The body of the function use the values from the optional parameters if they are provided, or fall back to `ctx`. The implementation function can be called from the implementation function of any other starlark rule, passing in the attribute values as optional parameters.

- providing arguments as files: in `pkg_deb`, there are several attributes (e.g., `version`/`version_file`, `description`/`description_file`) that can be provided either as a literal string, or as a file. This allows one to, for example, use a genrule to generate a description, instead of having to have the description fixed at loading time.

**Comment by aiuto** [comment]
But what is the compelling use case for other rules to share implementation functions? I don't want to add complexity for a hypothetical need. There are too many other things to build.

As far as symlinks and empty_dirs go, I see them being replaced in pkg_* with the more structured pkg_filegroup work. That will allow better reuse. For that, we will certainly need sharable tooling to convert file groups into manifiests of what should be packaged. I would still be reluctant, however, to expose that as reusable outside the pkg_* rules. I would rather we add generic capabilities so that people don't have to poke into internals.

**Comment by guoshimin** [comment]
OK, the spirit of `pkg_filegroup` and friends is exactly what I was trying to do. I defined my own custom rule that returns a provider that describes symlinks and empty dirs. Currently there is no way to pass the information contained in the provider to `pkg_tar`. If you are planning to have `pkg_tar` accept `pkg_{filegroup,mkdirs,mklinks}`, that will solve my problem nicely.

**Comment by aiuto** [comment]
Yes. The explicit plan is that pkg_* should accept all of the pkg_filegroup/dirs/links  combinations.
Or, to put it differently, every pkg_* will accept srcs that provide PackageFileInfo (and siblings).
It will use that shared Provider to figure out how to map source files and targets into the image.

And... you can obviously create your own rules that provide PackageFileInfo, so you can do new thinks.

**Comment by aiuto** [comment]
I'm closing this out for now as it is not specific enough.
- We do have ways to very dynamically change the output file names without using a genrule
- We could apply the same renaming templates to any specific attributes we want
- As people have specific needs for dynamically defined args, let's do separate issues for each.
