### ISSUE TITLE
rules_pkg-0.2.6.tar.gz not redistributable — missing license file

### ISSUE THREAD

**Issue by vonschultz** [bazelbuild/rules_pkg#231]
The release https://github.com/bazelbuild/rules_pkg/releases/download/0.2.6-1/rules_pkg-0.2.6.tar.gz is missing a license file. According to https://github.com/bazelbuild/rules_pkg/blob/0.2.6-1/LICENSE it is licensed under the Apache 2.0 license, and according to § 4a of the license
 
>      (a) You must give any other recipients of the Work or
>          Derivative Works a copy of this License; and

In order for rules_pkg-0.2.6.tar.gz to be redistributable a copy of the LICENSE file should be included in the tarball.

**Comment by aiuto** [comment]
Yes. I see what went wrong there.
