### ISSUE TITLE
//experimental/tests/rpm:test_rpm_manifest is linux only

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#255]
The bash script expects the tool md5sum to be present on the machine. On mac it is md5.  We could make a portable version in python.

**Comment by aiuto** [comment]
My current thinking is that we just add md5 to the rpmbuild toolchain today. There is little point in testing the manifest on windows or mac if we can't build it there. At least we can make the test skippable based on toolchain.

**Comment by nacl** [comment]
My understanding is that the rpmbuild toolchain is specifically for building RPM packages.  Taking the MD5 of files is not required for this, so I don't think `md5sum` or anything similar should be added there.

As for a common tool, my mac laptop (running 11.2) has a `/usr/bin/openssl`.  It's relatively common on Linux platforms, so  Perhaps that would be a good alternative to `md5sum` from GNU coreutils?  We could also write one in python too (it's cheap enough)

All that being said, I think the best option for now would be to make the manifest building Linux-only until we can explore sandboxing `rpmbuild` more completely.

**Comment by aiuto** [comment]
That logic sounds fine.  I would rather just see a python md5sum instead of
hoping openssl is there. That will often be a problem for windows.
