### ISSUE TITLE
I've forked deb_packages part

### ISSUE THREAD

**Issue by aisbaa** [bazelbuild/rules_pkg#259]
Hi, I've worked a little bit on deb_packages part in a forked repo [aisbaa/deb_packages](https://github.com/aisbaa/deb_packages). I'm planning to maintain this code, but before I continue I'd like to know if this is okay from legal perspective.

Context: https://github.com/bazelbuild/rules_pkg/issues/48

**Comment by aiuto** [comment]
Cool.  You should work with the CI team to set up a buildkite run for this.
https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md

**Comment by aisbaa** [comment]
Awesome, I'll look at it over the weekend.

**Comment by aiuto** [comment]
There is also  https://github.com/mariusgrigoriu/rules_dpkg
