### ISSUE TITLE
update_deb_packages should depends on https://github.com/bazelbuild/buildtools/

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/rules_pkg#294]
I don't think having update_deb_packages depending on build tools being installed in PATH is hermetic.

Instead, we can make it so that https://github.com/bazelbuild/rules_pkg/blob/main/deb_packages/tools/update_deb_packages/src/update_deb_packages.go takes argument which is path to `buildozer` and set it default to buildtools path.

Alternatively, instead of invoking the buildozer via `os.Exec()`, we can import `github.com/bazelbuild/buildtools/edit` and just use the golang API directly?

Let me know which approach is more comfortable to you guys. I can follow up with a PR.

**Comment by sluongng** [comment]
actually after reading https://github.com/bazelbuild/rules_pkg/issues/259 I realized that the `deb_packages` path is mostly unmaintained and has been forked by folks. 🤔 

Perhaps some note in the README.md would be nice to have.

**Comment by aiuto** [comment]
I'm closing this out. I'm happy to review a PR from aisbaa that updates the README.
