### ISSUE TITLE
pkg_tar package_dir parameter is encoded with the platform specific folder delimiters

### ISSUE THREAD

**Issue by konste** [bazelbuild/rules_pkg#297]
When `pkg_tar` is executed on Windows host and it has `package_dir` specified (like `a/b/c`) folder separators in `package_dir` are encoded in the resulting TAR in a platform specific way, i.e. on Windows they are encoded as backslashes. When that TAR is then expanded on Linux or Mac they don't understand backslashes and the content gets expanded to the wrong folder tree. 

The result of pkg_tar should not depend on the platform it runs on. Folder separators should always be slashes, not backslashes, and then the resulting TAR would be perfectly usable on all platforms.

**Comment by aiuto** [comment]
Hmmm... I thought I had that right the first time.  I'm trying to rebuild my windows environment (lost when working from home started) and don't have a dev machine right now. Can you send along a small tar file produced on windows so I can do some forensics?

**Comment by konste** [comment]
I am working on a repro.

**Comment by aiuto** [comment]
thanks
