### ISSUE TITLE
Set RPM_CONFIGDIR (and/or other env variables) when running rpmbuild

### ISSUE THREAD

**Issue by marcinkosiba** [bazelbuild/rules_pkg#327]
The purpose of this issue is to discuss implementation. I'd like to submit a PR which implements what we agree on here.

## Problem
We're using a prebuilt rpmbuild distributed as an http_archive. This gets un-zipped as part of the build, which means we don't know the path to the `rpmrc` file in advance (and therefore can't bake it into the binary). The `make_rpm.py` tool runs rpmbuild from a tmpdir, which makes looking up the relevant path in a wrapper script more challenging.

## Proposed solution
I'd like to add an `env` attribute to `rpmbuild_toolchain` and having `make_rpm.py` forward those when running rpmbuild.

I imagine anyone who is using a prebuilt rpm archive or building rpm from source will want to set these env vars, so I'd like to also propose auto-detecting RPM_CONFIGDIR if:
 - the `rpmbuild_toolchain` label attribute is used,
 - the RPM_CONFIGDIR env var is not in the `env` attribute.
The detection would be very simple - find the directory that contains `rpmrc` and set the env var to that.

**Comment by nacl** [comment]
I'm curious about your setup.  Internally, we use something similar, and have had to write scripts to work around `rpmbuild`'s assumptions of where things are beyond the config directory.  In particular, we also have to override the RPM database configuration, which, best I can tell, can only be done via command-line arguments and macros.  Did you need something similar in your implementation?

Regardless, we've had success with using a wrapper script that sets up calls to `rpmbuild` using the bash [runfiles library] in our custom (old) copy of rules\_pkg that accepts `rpmbuild` as a label input to `pkg_rpm`.  It should also work with the toolchain approach currently in rules_pkg, but I encountered an odd runfiles problem when I tried integrating it yesterday.  I need to confirm this, and will publish a ticket and a PR with a workaround shortly.

Does the wrapper script approach seem reasonable for you?  I'm personally feeling disinclined to add something like this to the `rpmbuild` toolchain when there is an adequate solution to this problem at the rule level

I think the core of this issue (how to configure a custom rpmbuild setup) can be solved with documentation and examples.  I've pondered publishing a summary of how we do it, but I haven't found the time.  Thoughts?

---

BTW, this `RPM_CONFIGDIR` environment variable is news to me, and actually would have saved me some time a while back -- there doesn't seem to be external-facing documentation for it.  Thanks for the pointer!

[runfiles library]: https://github.com/bazelbuild/bazel/blob/master/tools/bash/runfiles/runfiles.bash

**Comment by marcinkosiba** [comment]
Thank you for the detailed reply.

> I'm curious about your setup.
Sure! 
We build a statically-linked rpm executable from source on an ubuntu-based Docker image (happy to share the script for this if it helps someone). We `tar` that up with corresponding WORKSPACE/BUILD/wrapper_script.bzl files and upload to a server. At the moment only a single target, the rpmbuild wrapper, is public. Repositories which want to use the prebuilt rpmbuild pull it in as an `http_archive`.

The wrapper bash script is very simple - it sets the RPM_CONFIGDIR environment variable and then immediately execs the actual rpmbuild binary. The script is written written to disk from within a Starlark rule.

> we also have to override the RPM database configuration

At the moment we're only creating rpm packages and have not run into errors related to the database location. I'm sure that will come as more internal projects try and use this solutions.

> Issue #328

Aaah.. interesting! This was likely the root cause of some of my frustrations. Initially I tried to use a `sh_binary` wrapper and also had problems with runfiles.

> Does the wrapper script approach seem reasonable for you?

Yes, that makes sense.

> I've pondered publishing a summary of how we do it, but I haven't found the time. Thoughts?

Me from the past would have found that valuable. Happy to help with this.

**Comment by nacl** [comment]
I plan on moving this discussion to https://github.com/bazelbuild/rules_pkg/issues/29, but I need to get some time to start the discussion points and add in acceptance criteria.

**Comment by marcinkosiba** [comment]
Ok, had a shot at using new rules_pkg with the fix to Issue #328 and it is now possible to easily wrap the rpmbuild tool execution in an sh_binary, so I'll close the issue.

I also found a few more rough edges to using a prebuilt rpmbuild:
* it's rather complicated to change the prefix path that gets baked into the binary. Whatever I pass in to `./configure --prefix` gets baked into the macro files. Because macro files are evaluated eagerly and the path gets "propagated" to multiple values, it's not possible to easily amend it by passing another macro file via the `--load` argument. I think this would require generating the macro files in a separate step (probably a genrule). In other words a more portable rpmbuild needs the "standard" macro files to be generated dynamically,
* I'm sure there are similar issues around rpmdb, I haven't used any rpm/rpmbuild features that would require interacting with it though.

I think having this captured in documentation, along with a suggested rpmbuild.sh wrapper that contains known workarounds will save other engineers the trouble of discovering these issues on their own.

> I plan on moving this discussion to #29, but I need to get some time to start the discussion points and add in acceptance criteria.

Happy to continue the conversation there!
