### ISSUE TITLE
pkg_filegroup and related pkg_rpm rule should be stardoc'd

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#336]
There are rules that invoke stardoc in `pkg/distro/BUILD` for all the main rulesets in `pkg.bzl`.

It looks like I missed this for the rules I've been adding, so let's add them in when convenient.

**Comment by nacl** [comment]
Likely needed for 1.0

**Comment by aiuto** [comment]
Seems fixed. https://bazelbuild.github.io/rules_pkg/latest.html#pkg_filegroup
