### ISSUE TITLE
Package runfiles along with C++ binaries in pkg_* rules

### ISSUE THREAD

**Issue by sharvil** [bazelbuild/rules_pkg#339]
### Description of the problem / feature request / question:

(https://groups.google.com/forum/#!topic/bazel-discuss/5r_Ajw_j-ZI for context)

The current pkg_* rules don't package runfiles along with C++ binaries. This behavior makes it difficult to deploy an entire C++ application to machines that don't have source access.

Can we update the packaging rules to include runfiles along with binaries?

### Environment info
* Operating System:
MacOS 10.13.2

* Bazel version (output of `bazel info release`):
release 0.8.1-homebrew

**Comment by aiuto** [comment]
Folding this into #153

**Comment by hrvolapeter** [comment]
> Actually, it should be easy to implement `pkg_runfiles` in Starlark:
> 
> * [`DefaultInfo.data_runfiles`](https://docs.bazel.build/versions/master/skylark/lib/DefaultInfo.html#data_runfiles) (or [`DefaultInfo.default_runfiles`](https://docs.bazel.build/versions/master/skylark/lib/DefaultInfo.html#default_runfiles)?) contains the File objects for the runfiles
> * [`FilesToRunProvider.runfiles_manifest`](https://docs.bazel.build/versions/master/skylark/lib/FilesToRunProvider.html#runfiles_manifest) contains File object for the runfiles manifest
> * It should be easy to implement a custom C++ binary or Bash script that can parse a runfiles manifest and tars/zips up the runfiles it references
> * Using that binary/script, our hypothetical `pkg_runfiles` rule could create a `ctx.actions.run` / `ctx.actions.run_shell` with the binary/script, pass all the File objects for the runfiles and the manifest as inputs, and expect just a tar or zip as the output.
> 
> WDYT?

@laszlocsomor I'm a bit late to the party, is this still the best alternative?

The #153 is still ongoing work and the proposal from @benjaminp were accepted (links for proposals are dead) but the runfiles_manifest has still absolute paths, what's the current best way to package runfiles in Docker for python

**Comment by aiuto** [comment]
Please let's have any more discussion in #153.
It's not that it is hard to just get the runfiles into the tar file, an existing flag does this.
The hard part is a design that lets you conveniently move data and shared libraries to distinct places as appropriate for your target OS.
