### ISSUE TITLE
There should be a single file zip rule

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#352]
To build some items like a Unix manual page, we want to simply gzip a file. That is, the source is "myprog.1" and the rule should generate "myprog.1.gz".   Some ideas:
- a rule with a single src and out
- an attribute on pkg_files to specify zipping each
- a variation of pkg_zip that does many inputs with many outputs, producing a PackageFilesInfo
There are obvious tradeoffs w.r.t. actions to compress first and sending compressed files to the final package maker vs. just sending the files to the package maker and having it do it.

**Comment by mzeren-vmw** [comment]
Since this is about "final layout of files", perhaps this functionality should be a per-file option in "pkg_install" ?

**Comment by aiuto** [comment]
I think that's an additional place where it has to work. If we are installing direct from the workspace maybe it's a single rule.
```
pkg_install(... srcs=[foo.1], dest=/usr/man/man1, compress=gz)
```
but maybe pkg_install works just like pkg_rpm and points to a set of srcs that know where they go in the system tree.
```
pkg_files(name='manpages', srcs=[foo.1], prefix='/usr/man/man1', compress=gz)
pkg_install(..., srcs=[manpages, bins, ...], prefix=/tmp/fakeroot)
```

**Comment by aiuto** [comment]
This seems like overbuilding without a real need.  Downgrading priority, but we should probably close it as pointless.

**Comment by aiuto** [comment]
Closing issues that no one is likely to work on for any forseable future
