### ISSUE TITLE
Make template extensions more consistent

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#382]
Most of bazel proper uses `.tpl` extensions for templates, with `.tmpl` sprinkled in.  `.in` is for third-party code.

We have not done the same for rules_pkg: some code prefers `.in`, and others prefer `.tmpl`.

Perhaps we should standardize on `.tpl`?

Inspired by https://github.com/bazelbuild/rules_pkg/pull/380#discussion_r669269092

**Comment by aiuto** [comment]
I'm happy with .tpl.   This all works better when all rule sources use similar patterns, so I'm happy to do things the Bazel source way. 
I'll send you a cleanup PR that hits files independent of this PR later today.
