### ISSUE TITLE
Transitive debian package rule?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_pkg#39]
My modus operandi thus far for creating docker images that have complex debian dependencies is to manually resolve each one individually by going through (for example) https://packages.debian.org/stretch/git and following all the dependencies.  Rather painful.

There may be a ruleset out there that does this transitive search already.  If so, can someone provide an example?  

If not, are people interested in such a rule?

**Comment by MarkusTeufelberger** [comment]
Might be a bit more complex than expected with the "requires", "recommends" etc. sections as well as alternatives for various packages (java oracle or openjdk?).

Random web search result: https://www.techrepublic.com/article/how-to-check-package-dependencies-with-apt-rdepends/ - so in general this already should be possible and there are programs to do this.

**Comment by Globegitter** [comment]
Yep, I would definitely be interested in such a set of rules.

**Comment by huan086** [comment]
As a workaround, I'm using this to find all the Dependencies and PreDependencies

```sh
apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances \
    the-dep-packages | \
    grep -vE '^(ca-certificates|base-files|netbase|tzdata|libc6|libssl1\.1|openssl|\W)' | \
    sort -u
```

I'm assuming that the Docker image is [distroless base](https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md), thus I've used `grep` to exclude the libraries that are already installed, namely ca-certificates, base-files, netbase, tzdata, libc6, libssl1.1, openssl. Customize the regex to the Docker image you are using accordingly.

Credits: https://ostechnix.com/download-recursive-dependencies-of-a-package-in-ubuntu/

**Comment by aiuto** [comment]
Closing as obsolete. The docker building rules have forked to https://github.com/aisbaa/deb_packages.  #259
