### ISSUE TITLE
Remove PackageArtifactInfo

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#396]
Packaging rules typically emit two artifacts, one named after the rule's `name` and is overall easy to identify, and one that is templated with a bunch of other metadata, like timestamps, change numbers, and versions, and is not so easy to identify programatically.

`PackageArtifactInfo` helps alleviate this problem by giving users a provider interface for identifying the complex-named artifact.  Accessing it, however, requires that users implement custom rule logic to access it.

One potential way for working around this is use [output groups](https://docs.bazel.build/versions/main/skylark/rules.html#requesting-output-files).  These can emitted in the appropriate providers, and then specific artifacts can be consumed by specifying the `output_group` attribute of the [`filegroup`](https://docs.bazel.build/versions/main/be/general.html#filegroup.output_group) rule, with no custom rule logic required.

**Comment by aiuto** [comment]
Perhaps drop PackageArtifactInfo.

**Comment by aiuto** [comment]
Also see: https://github.com/bazelbuild/bazel/issues/14204

**Comment by aiuto** [comment]
The more I look at this, OutputGroupInfo is the way to specify outputs.
#484 shows why in examples/where_is_my_output.

**Comment by nacl** [comment]
Another complication (and I think we had this problem regardless) is how to direct different implicit outputs to different locations.  With this, you'd either have to create your own custom rule that maps everything to the right locations and emits `PackageFilesInfo` or somesuch, or have a lot of `filegroup`+`pkg_files` boilerplate.

It might be worth creating an more specific example use case for this.  #484 may be it, but even if it isn't it is definitely a step in the right direction.

**Comment by aiuto** [comment]
The more I look at the practicalities of it, the more I think that
OutputGroupInfo with consistent names for each group is the right choice. I
came up with PackageArtifactInfo as an alternative, but it is less useful
than OutputGroupInfo because you can't get at the individual components
easily from another rule or from the command line.

**Comment by aiuto** [comment]
Trying to decide what do to here.  I am in favor of removing `PackageFilesInfo` because OutputGroup does everything needed. The less we build new, the better.

**Comment by aiuto** [comment]
I changed this task to deleting PackageFilesInfo.  It was overdesigned.

**Comment by SanjayVas** [comment]
For those of us who had rule implementations that were relying on PackageArtifactInfo to get the archive file, what's the new approach?

**Comment by aiuto** [comment]
You look at the named entries of OutputGroupInfo.

**Comment by SanjayVas** [comment]
> You look at the named entries of OutputGroupInfo.

AFAICT there is no `OutputGroupInfo` entry for the archive `File` from `pkg_tar`. I assume in this case it would just be assuming that the `DefaultInfo` only includes one `File`, and that `File` is the archive?

**Comment by aiuto** [comment]
The default outputs for rules should always be in DefaultInfo.

For pkg_tar, the secondary output some people might want is the manifest.
That is returned here https://github.com/bazelbuild/rules_pkg/blob/ddaa10187a9e9687c7ef8fafdf42bb370bc7af53/pkg/private/tar/tar.bzl#L214

The original intent for PackageArtifactInfo was to return things like the extra outputs of .deb file building. DefaultInfo only has the .deb file, so other rules that depend on it get the thing they usually want. But making up a totally new provider to do what OutputGroupInfo does added needless complexity.
