### ISSUE TITLE
pkg_tar should not strip top level dirname from tree artifacts

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#404]
When we have a tree artifact as input, we strip the top level name.
That is not always appropriate.

**Comment by nacl** [comment]
I think I resolved this with `renames` and `REMOVE_BASE_DIRECTORY` in 760536837d5770f23e8520a9aa778d997712561f, but it does not yet allow for squashing multiple outputs in a single directory.   It might not be the best solution, but it should work.

Please confirm.

**Comment by aiuto** [comment]
Maybe. But we still have a problem with pkg_tar directly consuming tree artifacts.

So, I think the pkg_tar needs to change to not strip the tree, and if you want it gone, you can wrap with pkg_files to remove a level.
