### ISSUE TITLE
Cannot use `out` to set file name in `pkg_zip`

### ISSUE THREAD

**Issue by criemen** [bazelbuild/rules_pkg#414]
The docs of `pkg_zip` say
> Use out or package_file_name to specify the output file name

However, using out results in

```
ERROR: Traceback (most recent call last):
        File "/workspaces/semmle-code/extractor-python/BUILD.bazel", line 73, column 5, in <toplevel>
                dist(
        File "/workspaces/semmle-code/common.bzl", line 12, column 12, in dist
                pkg_zip(name = name + ".zip", out = name, srcs = [name])
        File "/home/codespace/.cache/bazel/_bazel_codespace/3c41b00dfcd8c4fb714360e042371c98/external/rules_pkg/pkg.bzl", line 723, column 17, in pkg_zip
                pkg_zip_impl(
Error in pkg_zip_impl: rule(...) got multiple values for parameter 'out'
```

Presumably this is because `out` is unconditionally set. Instead, it should do something ala
```
if not kwargs.get("out"):
  kwargs["out"] = archive_name + "." + extension
```
instead.

**Comment by aiuto** [comment]
`out` is deprecated.  Use `package_file_name` 
- https://github.com/bazelbuild/rules_pkg/blob/main/pkg/docs/reference.md#common-attributes
- https://github.com/bazelbuild/rules_pkg/tree/main/examples/naming_package_files

I should fix the documentation, and have the rule stop using it.

**Comment by criemen** [comment]
I have a rule ala
```
pkg_zip(name = "bla.zip", package_file_name = "bla.zip", srcs = [...])
```
Because the name of the rule is `bla.zip`, the rule creates an out file with name `bla.zip.zip`. Due to `package_file_name`, this file gets renamed to `bla.zip` (great), but I _also_ get a symlink from `bla.zip.zip` to `bla.zip`. Without overwriting `out`, it is not possible to get rid of this symlink.
It's not a big issue, as I can just ignore the symlink, but it is not as pretty as it could be, either.

**Comment by beasleyr-vmw** [comment]
> `out` is deprecated. Use `package_file_name`
> 
> * https://github.com/bazelbuild/rules_pkg/blob/main/pkg/docs/reference.md#common-attributes
> * https://github.com/bazelbuild/rules_pkg/tree/main/examples/naming_package_files
> 
> I should fix the documentation, and have the rule stop using it.

So, I ran into an small perf problem related to this. I have a 2+ GiB .zip created by pkg_zip. By not allowing me to use `out`, I'm forced into `setup_output_files`'s `ctx.symlink` path, which then incurs a 15s critical path tax. One wouldn't expect "Creating symlink foo.zip" to take 15s, but I can only assume that Bazel is (re-)checksumming the symlink target or similar. (See profile snippet below.) Until this is addressed (in Bazel?), I'd still like to have an escape hatch to avoid (in our case unused) symlinks.

```
Creating symlink bazel-out/k8-dbg-obj/bin/foo.zip
Category | action dependency checking
```

**Comment by aiuto** [comment]
I'm floored. That seems so wrong. 
Are you willing to make a reproduction to file against bazel?
