### ISSUE TITLE
Add ability to push debs and rpms to Google Artifact Registry (also: should we?)

### ISSUE THREAD

**Issue by symbiont-ji** [bazelbuild/rules_pkg#417]
I would like to add rules to push debs and rpms to the [Google Artifact Registry](https://cloud.google.com/artifact-registry).

1. Is this a good idea in the first place? Has it been discussed and rejected already?
2. Is anyone working on it? If not, I would like to volunteer to do it.
3. I assume the proper way to do this would be to create corresponding toolchains, so that support for, for example, Jfrog Artifactory can be added at a future time.

`rules_docker` have `container_push`, so there is precedent for bazel rules to publish to artifact repos.

**Comment by symbiont-ji** [comment]
Good point on the location. There are approximately aleph-naught repos under https://github.com/google/, do you have a particular one in mind? Of course I can just make my own (public eventually) repo!

I assume your implicit answer to 1 is "yes", any feedback on 2 and 3?

Thanks!

**Comment by aiuto** [comment]
Well, the answer to 1 is really a function of demand vs. development cost. I have no way to judge the demand for this feature. It is the first I have heard of it.
For 2, I don't know of anyone working on it. The Bazel team is working on structural changes to be able to create a debian packaging for Bazel that can be upstreamed, but that only addresses issues like code provenance and how dependencies are specified. Pushing to the repo is not in scope.
For 3, yes toolchains to do the pushing would be the right way to go.
