### ISSUE TITLE
Adjust attribute names to better match style guide (e.g. src in pkg_mklink)

### ISSUE THREAD

**Issue by nacl** [bazelbuild/rules_pkg#480]
According to the [.bzl style guide](https://docs.bazel.build/versions/main/skylark/bzl-style.html), attributes named `srcs` should be considered labels pointing to inputs.

`rules_pkg` is kinda odd in this respect -- `srcs` either refers to input files and/or packaging inputs (e.g. something with `PackageFilesInfo`).

One example that is perhaps problematic is `src` in `pkg_mklink`: internally we use `src` as a convention for a rule input that takes a single label/file, but `pkg_mklink` sets that to a string.  This has confused aspects that rely on these conventions.

Consider changing the rule attributes and provide a migration path.  This should be done prior to 1.0 if possible.

**Comment by aiuto** [comment]
srcs is fine for pointing to PackageFilesInfo.
Why don't we just make pkg_mklinks use target instead of src. We can support both for a while and remove src at 2.x so it is not so much of a breaking change.
