### ISSUE TITLE
Incorrect stretch PGP key used in WORKSPACE

### ISSUE THREAD

**Issue by mrinalwadhwa** [bazelbuild/rules_pkg#5]
I suspect this https://github.com/bazelbuild/rules_pkg/blob/0634eaf3ad604aca626dc74a2d4fa85c36210872/WORKSPACE#L145 was meant to be `stretch_archive_key` and not `jessie_archive_key`

If it works that is likely just accidental.

**Comment by mrinalwadhwa** [comment]
turns out `jessie_archive_key` is the one that works.
If I use `stretch_archive_key` even when the distro is stretch, I get ...
```
2018/01/24 20:40:52 openpgp: signature made by unknown entity
```

**Comment by Globegitter** [comment]
Yep, I ran into the same issue, `stretch_archive_key` did not work for me when distro was stetch but `jessie_archive_key` did.
