### ISSUE TITLE
pkg_tar stamp default value is inconsistent with documentation

### ISSUE THREAD

**Issue by alokpr** [bazelbuild/rules_pkg#501]
According to `pkg_tar` documentation, the default value of `stamp` should be -1 (which makes perfect sense).
However the actual default value is 0 (which is inconvenient).

https://github.com/bazelbuild/rules_pkg/blob/0.5.1/pkg/docs/reference.md#pkg_tar
https://github.com/bazelbuild/rules_pkg/blob/0.5.1/pkg/pkg.bzl#L447

**Comment by aiuto** [comment]
The documentation is wrong. The default should be 0.
The current docs do show 0, but have other formatting problems.
https://github.com/bazelbuild/rules_pkg/blob/main/docs/latest.md

**Comment by aiuto** [comment]
0 is the default because that causes the least surprise because it only impacts pieces of your build where you have enabled it

**Comment by aiuto** [comment]
Fixed in #509
