### ISSUE TITLE
shell env is not available when building a debian package using pkg_deb

### ISSUE THREAD

**Issue by deepakm37** [bazelbuild/rules_pkg#52]
### Description of the problem / feature request:

When building a debian package with pkg_deb(), the shell env is not made available to the execution context. As such, the python implementation defaults to using `/usr/bin/python` instead of using one from the PATH. This is an issue because the system default python (located at `/usr/bin/python`) is super old and I had to install a newer version separately to run any newer python code. This newer path is on the PATH, but it isn't available for pkg_deb.

I noticed that this is likely due to the missing `"use_default_shell_env = True"` in the action "MakeDeb" in `bazel/tools/build_defs/pkg/pkg.bzl`. The same is present in "MakeRpm" in `bazel/tools/build_defs/pkg/rpm.bzl` and pkg_rpm works just fine.

I also tried using `--action_env=PATH` but that had no effect.

### Feature requests: what underlying problem are you trying to solve with this feature?

Missing shell env in the context of "MakeDeb".

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Install python separately from the system installation. If the system installed version of Python is old, or isn't available, running a pkg_deb() rule will throw an error that looks like:

---
With no system installed Python:
```
(cd /home/root/.cache/bazel/_bazel_root/2b1aa6f981717219f7c66311e2227f1d/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb ...
 ...)

ERROR: BUILD.bazel:84:1: MakeDeb packages/x_1_amd64.deb failed (Exit 127)
/usr/bin/env: python: No such file or directory
Target //packages:x-deb failed to build
```
----
OR with an older Python (e.g. Python 2.6):
```
(cd /home/root/.cache/bazel/_bazel_root/2b1aa6f981717219f7c66311e2227f1d/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb ...
 ...)
 
ERROR: BUILD.bazel:84:1: MakeDeb packages/x_1_amd64.deb failed (Exit 1)
  File "/home/root/.cache/bazel/_bazel_root/2b1aa6f981717219f7c66311e2227f1d/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 211
    checksums = {k: fn() for (k, fn) in hash_fns.items()}
                           ^
SyntaxError: invalid syntax
Target //packages:x-deb failed to build
```

### What operating system are you running Bazel on?

CentOS 6.10

### What's the output of `bazel info release`?

release 0.17.2- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Compiled Bazel from source, following the instructions at https://docs.bazel.build/versions/master/install-compile-source.html

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

Not much around this issue. Somewhat related issue at a general level seems to be: https://github.com/bazelbuild/bazel/issues/4137, which is not directly about "MakeDeb".

### Any other information, logs, or outputs that you want to share?

---

**Comment by aiuto** [comment]
See also #180

**Comment by aiuto** [comment]
Closing as obsolete.
- The python toolchain setup has changed tremendously since then.
- Tools should not get python from PATH.  The python toolchain should auto-detect from PATH, but that is not the problem of the packaging rules.

**Comment by deepakm37** [comment]
I understand a lot has changed in the Python toolchain detection, and that it is not really the problem with pkg rules with Python path isn't being detected properly.

However, I'm curious about the reasons for using `use_default_shell_env = True` in other rules such as `PackageTar`, `PackageZip` in `pkg.bzl` but not `MakeDeb`? Why not also use it in `MakeDeb` if there is no specific reason?

FYI, with Bazel 4.0 and `rules_pkg v0.4.0`, I still see the same error when generating a deb package, but all works fine for an rpm or tar package.

**Comment by aiuto** [comment]
To be totally honest about it, there was little design of the features when they were stuffed into Bazel 5 or 6 years ago. There is an inconsistent mix of behaviors that I am trying to normalize. 
Or to put it a different way, I haven't the faintest idea why some set use_default_shell_env=True. There is no design doc to go from and I have little hope of finding a reason other than to read years of PR logs back from when the code was part of Blaze. Even if I tried to do that, I don't have big hope I would find any concrete reason.

**Comment by deepakm37** [comment]
In that case, would it make sense to add `use_default_shell_env = True` for `MakeDeb`? This makes the behavior of all rules within `pkg.bzl` consistent, and they would all work or fail the same way. At least this solves a particular problem I'm facing, without changing the behavior in other cases. This really is a one-line addition, and I'm happy to send a PR.

**Comment by aiuto** [comment]
I would actually rather go the other way and remove it from pkg_tar.
