### ISSUE TITLE
pkg_rpm doesn't set architecture in RPM metadata

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/rules_pkg#54]
### Description of the problem / feature request:
I've created a `pkg_rpm` target which sets the `architecture` attribute to something other than the default (e.g. `aarch64`).

After building the RPM, if I query it using the `rpm` tool, it displays the wrong architecture (presumably using the host arch instead):
```console
$ rpm -q --info bazel-bin/build/rpms/kubectl.rpm
Name        : kubectl
Version     : 1.15.0~alpha.0.328+caa70952409c03
Release     : 00
Architecture: x86_64
...
```

It looks like this is because the `make_rpm.py` script never actually passes the architecture to `rpmbuild`; this instance variable is never used:
https://github.com/bazelbuild/bazel/blob/6fc5b6e53be5f1b8b744789f35e1de6617ed7fe3/tools/build_defs/pkg/make_rpm.py#L187

### What operating system are you running Bazel on?

`Debian GNU/Linux rodete`

### What's the output of `bazel info release`?

`release 0.22.0`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:ixdy/kubernetes.git
a22763b24ee53b5efca5c60b000a63875a6b6f2a
caa70952409c03b099c9aa26abde9b2c77013f34
```

**Comment by aiuto** [comment]
If you get a chance, can you send a small repo against the pkg_rpm in this repo?
I am trying to add proper tests for pkg_rpm and AFAICT it simply does not work at all.
But I can't tell if that is me or it is really broken. I am not keen on applying #75 until I am confident that it will not break anyone.

**Comment by aiuto** [comment]
This was probably fixed. have to verify.

**Comment by aiuto** [comment]
Ping for verification

**Comment by nacl** [comment]
This is not believed to be a problem in current versions of rules_pkg.  We have test code that sets the architecture to `noarch`, and it is respected (and tested): 

https://github.com/bazelbuild/rules_pkg/blob/9748dfa1a9a884d4107e5980f4bb3fa330f18b15/pkg/tests/rpm/BUILD#L125-L145

If I change the architecture to something completely different (aarch64), I get output like this:

```
INFO: Analyzed target //tests/rpm:test_rpm (1 packages loaded, 9 targets configured).
INFO: Found 1 target...
INFO: From MakeRpm tests/rpm/test_rpm-1.1.1-2222.aarch64.rpm:
Error calling rpmbuild:
error: No compatible architectures found for build

No RPM file created.
ERROR: /Users/apsaltis/workspace-git/rules_pkg/pkg/tests/rpm/BUILD:125:8: output 'tests/rpm/test_rpm-1.1.1-2222.aarch64.rpm' was not created
ERROR: /Users/apsaltis/workspace-git/rules_pkg/pkg/tests/rpm/BUILD:125:8: MakeRpm tests/rpm/test_rpm-1.1.1-2222.aarch64.rpm failed: not all outputs were created or valid
Target //tests/rpm:test_rpm failed to build
```

This error is coming from `rpmbuild`, and thus proves that the architecture attribute is showing up as expected.  Fixing this problem (cross-building packages) is tracked in #323.
