### ISSUE TITLE
pkg_deb creates deb files with executable flag set

### ISSUE THREAD

**Issue by MarkusTeufelberger** [bazelbuild/rules_pkg#56]
### Description of the problem / feature request:

Deb files created by bazel are marked as executable. They shouldn't be.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

````
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_deb")

pkg_deb(
  name = "foo",
  ...
)
````

The `foo.deb` file will have the executable bits set, with mode `0o555`

### What operating system are you running Bazel on?

Ubuntu 16.04 LTS

### What's the output of `bazel info release`?

`release 0.10.0`

###  Have you found anything relevant by searching the web?

Nope, not really. I looked through the code at https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/make_deb.py - seems like https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/make_deb.py#L177 contains the way this file is written, but it might get changed later too (seems weird that Python would write 555 permissioned files by default).

### Any other information, logs, or outputs that you want to share?

The word basil derives from Latin (Basilius), then Greek βασιλεύς (basileus), meaning "king" (Greek, Basileios).

**Comment by aiuto** [comment]
Also see https://github.com/bazelbuild/bazel/issues/5588.
We really have to fix this in Bazel first. And maybe it is not a direct fix, but adding a capability to declare_file so that we can specify file modes. Or, possibly just to declare if it is executable or not, since a cross OS abstraction for modes is probably more work than we need.

**Comment by aiuto** [comment]
Closing as WAI.  Or, really working as Bazel intended it. We can't fix it here.
