### ISSUE TITLE
`pkg_zip` does not expand variables in `package_dir`

### ISSUE THREAD

**Issue by dlj-NaN** [bazelbuild/rules_pkg#578]
It is somewhat common for distribution archives to include paths with, say, an embedded version number. The `pkg_tar` rule expands `package_variables` in the `pacakge_dir`, similar to `package_file_name`. However, `pkg_zip` does not do the same expansion in its `package_dir`.

This seems like an oversight, since the functionality was only added to tar in #305, in response to #193. This should be fairly straightforward to port over to the `pkg_zip` rules.

**Comment by aiuto** [comment]
Fixed by #577
