### ISSUE TITLE
pkg_tar not built in sh_test data (or *_test)

### ISSUE THREAD

**Issue by zanes2016** [bazelbuild/rules_pkg#58]
### Description of the problem:

I'm trying to run an integration/unittest with a shell script that first untars a pacakge built with bazel. I would expect to simply be able to add the pkg_tar target in the sh_test's data field. However, this does not work. The pkg_tar is not built when running bazel test <path>:test. It works if the data target is a binary or filegroup, but not if it is a pkg_tar.

### A minimal example to reproduce the problem:
```
$ cat BUILD 
package(default_visibility = ["//visibility:public"])
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar", "pkg_deb")

pkg_tar(
  name = 'testPkg',
  strip_prefix = '/',
  package_dir = '/',
  files = [
    'test.txt',
  ],
)

sh_test(
  name = 'test',
  srcs = ['test.sh'],
  data = [':testPkg']
)
$
$ cat test.sh 
#!/bin/bash
set -e

echo hello world
ls
tar xvf test.tar
$
$ cat test.txt 
hello world
$
$
$ bazel test --test_output=all :test
...
INFO: From Testing //:test:
==================== Test output for //:test:
hello world
test
test.sh
tar: test.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
================================================================================
Target //:test up-to-date:
  bazel-bin/test
INFO: Elapsed time: 0.183s, Critical Path: 0.06s
//:test                                                                  FAILED in 0.1s
```
### Environment info
* Operating System:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

* Bazel version (output of `bazel info release`):
release 0.4.3

**Comment by aiuto** [comment]
This seems obsolete. It looks like a typo.
Also, there is now an OutputGroupInfo provider returned from pkg_tar.

**Comment by lazdmx** [comment]
Hmm... I got same problem and it I'm pretty sure that it looks like a bug (IMHO) I think it should be possible to reference a tar-file by name of the `pkg_tar` rule, not only by name of a file


```python
sh_binary(
    name = "builder",
    srcs = ["builder.sh"],
    data = ["pack.tar"], # <----- doesn't work with 'pack' label.  '.tar' suffix makes it work
)

pkg_tar(
    name = "pack",
    srcs = [":srcs"],
)
```


----

```
Build label: 1.2.0
Build time: Wed Nov 20 15:08:12 2019 (1574262492)
Build timestamp: 1574262492
Build timestamp as int: 1574262492
```
