### ISSUE TITLE
Deb Package Name Does Not Respect Architecture and Version from File

### ISSUE THREAD

**Issue by chenhao94** [bazelbuild/rules_pkg#583]
https://github.com/bazelbuild/rules_pkg/blob/6afea17ad3826119b349b4499db703ab7f71bb78/pkg/private/deb/deb.bzl#L25-L30

It happens before reading the files, so if both of arch and version are set from file, then the default output name will be `name__all.deb`

**Comment by aiuto** [comment]
Can you clarify that a bit more? 
Do you mean the .spec file?   That would not be possible because we have to name the output at analysis time and we can't read it until execution time.
Did you have something else in mind?

**Comment by chenhao94** [comment]
Here is a simple case to reproduce, maybe that will be clearer:

```
$ ls | xargs -I % bash -c "echo ====== % ======; cat %"
====== BUILD ======
load("@rules_pkg//:pkg.bzl", "pkg_deb", "pkg_tar")
                                                    
filegroup (
    name = "mydata",      
    srcs = ["mydata.txt"],
)

filegroup (
    name = "arch",
    srcs = ["arch.txt"],
)

filegroup (
    name = "version",
    srcs = ["version.txt"],
)

pkg_tar(
    name = "my_tar",
    srcs = [
        ":mydata",
    ],
    package_dir = "/usr/bin",
)

pkg_deb(
    name = "my_deb",
    data = ":my_tar",
    package = "my_deb",
    maintainer = "Me",
    description = "This is a test deb package.",
    architecture_file = ":arch",
    version_file = ":version",
)
====== WORKSPACE ======
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_pkg",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.7.0/rules_pkg-0.7.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.7.0/rules_pkg-0.7.0.tar.gz",
    ],
    sha256 = "8a298e832762eda1830597d64fe7db58178aa84cd5926d76d5b744d6558941c2",
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()
====== arch.txt ======
amd64
====== mydata.txt ======
====== version.txt ======
123.0
```

Then we generate the deb package:

```
$ bazel build :my_deb
INFO: Analyzed target //:my_deb (45 packages loaded, 334 targets configured).
INFO: Found 1 target...
Target //:my_deb up-to-date:
  bazel-bin/my_deb__all.deb
INFO: Elapsed time: 1.240s, Critical Path: 0.39s
INFO: 12 processes: 10 internal, 2 linux-sandbox.
INFO: Build completed successfully, 12 total actions
$ dpkg -I bazel-bin/my_deb__all.deb 
 new Debian package, version 2.0.
 size 10668 bytes: control archive=235 bytes.
     149 bytes,     7 lines      control              
 Package: my_deb
 Version: 123.0
 Section: contrib/devel
 Priority: optional
 Architecture: amd64
 Maintainer: Me
 Description: This is a test deb package.
```
As you can see, the dpkg info shows the correct arch (amd64) and version number (123.0), but the file name was wrong (arch "all" and the version is empty). We can manually fix it though

```
$ dpkg-name bazel-bin/my_deb__all.deb 
dpkg-name: info: moved 'my_deb__all.deb' to 'bazel-bin/my_deb_123.0_amd64.deb'
```

**Comment by aiuto** [comment]
Yes. This is the same as reading from the spec file. You can't read anything from a file and have it be in the name we create.  You need to use package_file_name and specify the version as an attribute or pull it in as a build time flag.  If you want to get the version from a different source than the BUILD file, perhaps to share a version number across many targets, put it in a .bzl file and load the variable out of that.

There are examples here. https://github.com/bazelbuild/rules_pkg/tree/main/examples/naming_package_files
