### ISSUE TITLE
pkg_tar gzip would be faster with a concurrent (pigz) mode

### ISSUE THREAD

**Issue by rmmh** [bazelbuild/rules_pkg#59]
pkg_tar uses Python's built-in tarfile module, and will only use a single CPU core for compression. If it worked in parallel (like pigz), it would be much faster.

As part of the Kubernetes build, we make a [300MB .tar.gz file](kubernetes-release/release/v1.6.0/kubernetes-server-linux-amd64.tar.gz) from 1.3GB of inputs. This step takes around 100 seconds.

```
$ pv kubernetes-server-linux-amd64.tar | gzip | wc -c
1.23GB 0:00:38 [32.9MB/s] [===>] 100%            
312612343
$ pv kubernetes-server-linux-amd64.tar | pigz | wc -c
1.23GB 0:00:05 [ 248MB/s] [===>] 100%            
311930961
```

**Comment by MarkusTeufelberger** [comment]
One thing that might be also to consider is reproducibility of the generated files.

**Comment by aiuto** [comment]
Design idea:  pkg_tar gets an 'compressor' attribute. This is label of an executable.
If provided, we do not pick a compression algorithm and do straight output, streaming the output of tarfile to the compressor and writing the result.

I'm not going to have time to do this, but I will happily review a PR that goes in that direction.  If the code is larger than the documentation and tests, I would be surprised.

**Comment by nacl** [comment]
I would be good with such a design.  GNU tar supports sort of thing.

A caveat WRT parallel compressors is that (last I checked) bazel does not know how to account for multiple CPUs scheduled to task(s) and using something like `pigz` can overschedule your system.  See also https://github.com/bazelbuild/bazel/issues/6477.

**Comment by aiuto** [comment]
I wonder if that is likely to matter.  The only time you should be compressing the archive is on the top level target. By that time no other actions should be executing.   To put it the other way around, if people are compressing intermediate targets just to uncompress them to repack them, they are assuming that they have much more CPU than disk bandwidth.

In any case, I don't want to make this our problem.  I'm happy to have the capability for someone to use their own compressor, but rules_pkg should not explicitly support pigz.  That way it's not a bug if pigz results in non-determinism or un-debuggable performance problems.  For X-windows fans, this is a case where we should opt for mechanism, not policy.

**Comment by nacl** [comment]
> I wonder if that is likely to matter. The only time you should be compressing the archive is on the top level target. By that time no other actions should be executing. To put it the other way around, if people are compressing intermediate targets just to uncompress them to repack them, they are assuming that they have much more CPU than disk bandwidth.
>

I'm not so sure.  As an example, our intended use case requires producing several packages from a single Bazel call.  Several of these are potentially large enough to benefit from parallelized compression.  Depending on how scheduling works out, there can be nontrivial overlapping between packaging and other compilation stages.

This has no bearing on the below, which makes perfect sense.

> In any case, I don't want to make this our problem. I'm happy to have the capability for someone to use their own compressor, but rules_pkg should not explicitly support pigz. That way it's not a bug if pigz results in non-determinism or un-debuggable performance problems. For X-windows fans, this is a case where we should opt for mechanism, not policy.

Agreed.

**Comment by MarkusTeufelberger** [comment]
I agree, if you have a large-ish monorepo (probably one of the main use cases for bazel to begin with) and you are producing e.g. deb packages for your individual pieces of software, I would expect that there's a lot of different `pkg_tar` targets being exercised at various times when some larger change is being built.
