### ISSUE TITLE
Cannot load '@rules_pkg//:mappings.bzl': no such file

### ISSUE THREAD

**Issue by seanschoi** [bazelbuild/rules_pkg#596]
Hello bazel team,

I am trying to use the rules_pkg on Bazel version 5.2.0.

I do have 0.7.0 version of rules package defined in WORKSPACE as follows:

`http_archive(
    name = "rules_pkg",
    sha256 = "8a298e832762eda1830597d64fe7db58178aa84cd5926d76d5b744d6558941c2",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.7.0/rules_pkg-0.7.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.7.0/rules_pkg-0.7.0.tar.gz",
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()
`

When I try to add  'load("@rules_pkg//:mappings.bzl", "pkg_filegroup")' to my BUILD, I am getting 'ERROR: error loading package '': cannot load '@rules_pkg//:mappings.bzl': no such file'.

Has anyone encountered this issue? Thank you

**Comment by aiuto** [comment]
you want @rules_pkg//*pkg*:mappings.bzl.

**Comment by khumps** [comment]
I am getting this same error, even with `load("@rules_pkg//pkg:mappings.bzl", "pkg_files")`

my WORKSPACE includes:
```
http_archive(
    name = "rules_pkg",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.7.1/rules_pkg-0.7.1.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.7.1/rules_pkg-0.7.1.tar.gz",
    ],
    sha256 = "451e08a4d78988c06fa3f9306ec813b836b1d076d0f055595444ba4ff22b867f",
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()
```

**Comment by aiuto** [comment]
I can't reproduce that. You probably are not actually getting rule_pkg
0.7.1.
I would bet that another repo is bringing in an obsolete version through
its dependency chain.

**Comment by phlax** [comment]
not sure if this resolves but would be good to clear up this mess - we havent been able to update rules_pkg for a year and a half

https://github.com/protocolbuffers/protobuf/pull/15481
