### ISSUE TITLE
package_dir attribute is not applied to pkg_mklink

### ISSUE THREAD

**Issue by ljessendk** [bazelbuild/rules_pkg#610]
I'm upgrading from rules_pkg 0.5.2 to rules_pkg 0.7.0 and trying to use the new "package_dir" parameter to add the "./" prefix that was removed as part of (https://github.com/bazelbuild/rules_pkg/issues/531).
But it seems that "package_dir" does not work with pkg_mklink.

The following code illustrates the problem:
```
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("@rules_pkg//:mappings.bzl", "pkg_mklink", "pkg_files")

pkg_files(
    name = "myfile_pkg",
    srcs = ["myfile"],
)

pkg_mklink(
    name = "mylink_lnk",
    link_name = "mylink",
    target = "myfile",
)

pkg_tar(
    name = "myarchive",
    srcs = ["myfile_pkg", "mylink_lnk"],
    package_dir = "."
)
```
Invoking
```
bazel build myarhive.tar
tar tf bazel-bin/myarchive.tar
```
Gives:
```
./myfile
mylink
```
I would have expected:
```
./myfile
./mylink
```

**Comment by aiuto** [comment]
Both are wrong.  It should be
```
myfile
mylink
```

The leading "./" on paths is not useful. Worse, having a single explicit "." could be dangerous if the untarring process changes permissions on the destination folder.

To me, the bug is that package_dir="." on tar is doing something, rather than being a no-op.

**Comment by ljessendk** [comment]
I agree that, in general, putting leading "./" is a bad idea, however:

- Being able to add a leading "./" is very useful if you, like me, need to create a .tar archive for a legacy system that expects a tar archive that contains files with a leading "./".
- Having filenames with "./" in a tar archive might not be best practice, but it is perfectly legal (this is what you get with 'tar cf archive.tar -C folder .').

Also it seems that rules_pkg intentionally supports the use case of having a leading "./" (see the test 'test_tar_leading_dotslash' in tests/tar/BUILD).
