### ISSUE TITLE
pkg_tar doesn't support directories anymore

### ISSUE THREAD

**Issue by iamricard** [bazelbuild/rules_pkg#611]
Hi 👋🏼 

We're trying to bump up to 0.7.0 from 0.2.6-1. We've run into a behavior change change for the `pkg_tar` rule. We had a target the declared two directories as its only srcs. This worked fine (even with nested BUILD files) and both directories got packaged. However, `pkg_tar` now throws if we pass directories directly as `srcs`. I created a repro repository: https://github.com/iamricard/rules_pkg_repro

There are two targets there: `//src:tar_0_7_0` and `//src:tar_0_6_0`, they use their respective versions of `rules_pkg` (this breaks in the new `tar_writer.py` file, added in 0.7.0). Outputs:

```
% b build //src:tar_0_7_0
INFO: Invocation ID: 0d25c0ae-41f7-489b-9b72-c742b743ad9f
INFO: Analyzed target //src:tar_0_7_0 (0 packages loaded, 1 target configured).
INFO: Found 1 target...
ERROR: /Users/ricard.sole/github/rules_pkg_repro/src/BUILD:14:14: Writing: bazel-out/darwin_arm64-fastbuild/bin/src/tar_0_7_0.tar failed: (Exit 1): build_tar failed: error executing command
  (cd /private/var/tmp/_bazel_ricard.sole/accb4123e903f679e064e9bf41c6d43f/sandbox/darwin-sandbox/5/execroot/rules_pkg_repro && \
  exec env - \
    PATH='<omitted>' \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_pkg_0_7_0/pkg/private/tar/build_tar '--output=bazel-out/darwin_arm64-fastbuild/bin/src/tar_0_7_0.tar' '--mode=0555' '--owner=0.0' '--owner_name=.' '--directory=/go/src/github.com/iamricard/rules_pkg_repro' '--mtime=portable' '--manifest=bazel-out/darwin_arm64-fastbuild/bin/src/tar_0_7_0.manifest')
# Configuration: 8c7c8a83495a6b29f5e61b94373e857884c6b6f4ed04fcd868a9a81a5d062e34
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_ricard.sole/accb4123e903f679e064e9bf41c6d43f/sandbox/darwin-sandbox/5/execroot/rules_pkg_repro/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_pkg_0_7_0/pkg/private/tar/build_tar.runfiles/rules_pkg_0_7_0/pkg/private/tar/build_tar.py", line 436, in <module>
    main()
  File "/private/var/tmp/_bazel_ricard.sole/accb4123e903f679e064e9bf41c6d43f/sandbox/darwin-sandbox/5/execroot/rules_pkg_repro/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_pkg_0_7_0/pkg/private/tar/build_tar.runfiles/rules_pkg_0_7_0/pkg/private/tar/build_tar.py", line 427, in main
    output.add_manifest_entry(entry, file_attributes)
  File "/private/var/tmp/_bazel_ricard.sole/accb4123e903f679e064e9bf41c6d43f/sandbox/darwin-sandbox/5/execroot/rules_pkg_repro/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_pkg_0_7_0/pkg/private/tar/build_tar.runfiles/rules_pkg_0_7_0/pkg/private/tar/build_tar.py", line 309, in add_manifest_entry
    self.add_file(entry.src, entry.dest, **attrs)
  File "/private/var/tmp/_bazel_ricard.sole/accb4123e903f679e064e9bf41c6d43f/sandbox/darwin-sandbox/5/execroot/rules_pkg_repro/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_pkg_0_7_0/pkg/private/tar/build_tar.runfiles/rules_pkg_0_7_0/pkg/private/tar/build_tar.py", line 98, in add_file
    self.tarfile.add_file(
  File "/private/var/tmp/_bazel_ricard.sole/accb4123e903f679e064e9bf41c6d43f/sandbox/darwin-sandbox/5/execroot/rules_pkg_repro/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_pkg_0_7_0/pkg/private/tar/build_tar.runfiles/rules_pkg_0_7_0/pkg/private/tar/tar_writer.py", line 241, in add_file
    with open(file_content, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: 'src/dir1'
Target //src:tar_0_7_0 failed to build
INFO: Elapsed time: 0.441s, Critical Path: 0.34s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully

% b build //src:tar_0_6_0
INFO: Invocation ID: cc7299ec-1448-4fd8-a504-9d08fa0455a3
INFO: Analyzed target //src:tar_0_6_0 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src:tar_0_6_0 up-to-date:
  bazel-bin/src/tar_0_6_0.tar
INFO: Elapsed time: 0.111s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

% tar -tf bazel-bin/tar_0_6_0.tar
./
./go/
./go/src/
./go/src/github.com/
./go/src/github.com/iamricard/
./go/src/github.com/iamricard/rules_pkg_repro/
./go/src/github.com/iamricard/rules_pkg_repro/dir1/
./go/src/github.com/iamricard/rules_pkg_repro/dir1/BUILD
./go/src/github.com/iamricard/rules_pkg_repro/dir1/subdir1/
./go/src/github.com/iamricard/rules_pkg_repro/dir1/subdir1/BUILD
./go/src/github.com/iamricard/rules_pkg_repro/dir1/subdir1/foo.md
./go/src/github.com/iamricard/rules_pkg_repro/dir2/
./go/src/github.com/iamricard/rules_pkg_repro/dir2/foo.py
./go/src/github.com/iamricard/rules_pkg_repro/dir2/foo_bar.py
./go/src/github.com/iamricard/rules_pkg_repro/dir2/subidr2/
./go/src/github.com/iamricard/rules_pkg_repro/dir2/subidr2/foo.txt
```

**Comment by aiuto** [comment]
This is WAI.
You can't just point to a directory and expect tar to glob it up.
You need a glob() in the srcs in some way.

**Comment by iamricard** [comment]
> This is WAI. You can't just point to a directory and expect tar to glob it up. You need a glob() in the srcs in some way.

🤔 it does seem like a breaking change though, doesn't it? documenting that this used to work and now it doesn't seems important. glob is significantly more inconvenient, since globs stops at bazel package boundaries. so starting 0.7.0 you'd need to have filegroups in every subdirectory.

also this seems to be an issue with tar_writer specifically no? when pkg_tar used build_tar directly this worked fine, it's the `open`ing the file that causes this

https://github.com/bazelbuild/rules_pkg/blob/main/pkg/private/tar/tar_writer.py#L242

**Comment by iamricard** [comment]
to be more specific, this broke in https://github.com/bazelbuild/rules_pkg/commit/e68e175f029d5bd6851cf46e8398d1f81e1c81c6, which i pushed here https://github.com/iamricard/rules_pkg_repro/commit/d36922e62752a40f22b2e957c75eea29ced50819

**Comment by iamricard** [comment]
digging more into this, it looks like the "is_directory" branch is not triggered when declaring a directory as a src https://github.com/bazelbuild/rules_pkg/blob/6fe8c2ed2550b51129e16dd7c80b0efd8a59129f/pkg/private/tar/tar.bzl#L139-L140

**Comment by aiuto** [comment]
True. It was a breaking change, but it was never explicitly allowed or tested behavior. It just happened to work.

It is also inherently non Bazel-ish in that it just pulls whatever it finds on the build machine, which could be different between any developer and/or the CI system. Explicit naming of files is the best way to go.  globs() are OK for some situations.  globs (or the old behavior) are almost always probably wrong when crossing package boundaries.

**Comment by iamricard** [comment]
Sorry to be a stick in the mud, but let's say we use `glob(["**/*"], exclude_directories = False)`. I'd expect this to at least not break, but it breaks the target. I understand this bazel mishandling globbed directories (https://github.com/bazelbuild/bazel/issues/12954) but this case _was_ correctly handled by rules_pkg prior to dropping `add_dir`. At the very least, documenting that `srcs` only works with _some_ kinds of labels would be nice (right now all the docs claim is that it takes a "[List of labels](https://bazel.build/docs/build-ref.html#labels)").

**Comment by iamricard** [comment]
In any case, I'll close this issue. For anyone searching: using directory labels _does_ work for generated directories which means that starting skylib 1.3.0 you can use `copy_directory` to achieve the same result. The repro repo has one final commit showing how https://github.com/iamricard/rules_pkg_repro/commit/c9385095288a44cccb448bf4c2e5e053fd4b695b.
