### ISSUE TITLE
Directory entries not added to zip contents

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_pkg#622]
When creating a zip using `pkg_zip` with files nested in a directory, the zip only contains the files, and not the entries for the directories. This causes unpacking to fail with some "unzip" implementations.

`pkg_zip` should create all the directory entries required for a file before adding that file to the zip.

**Comment by shs96c** [comment]
To be fair, this is the same as `zipper` from `@bazel_tools`, but it's not great for something that will be used to create artifacts for users.

**Comment by aiuto** [comment]
It's not the same zipper at all. Totally different code.

What particular unzip versions choke on this?

**Comment by shs96c** [comment]
I understand it's a different zip tool. I was saying that `zipper` shows the same behaviour. I should have been clearer. My apologies.

An obvious case where this fails is that a Spring web component may try and serve classpath resources. It tends to be configured by finding the directory containing the entries: if the directory entry isn't in the jar, this process will fail. A similar thing is done in [Selenium](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/web/GridUiRoute.java#L44) A jar is just a zip with a `.jar` extension.

From memory, I can't remember the specific zip tool that fails, but I've seen that fail in the wild.
