### ISSUE TITLE
pkg_tar ignores package_dir for symlinks

### ISSUE THREAD

**Issue by hidmic** [bazelbuild/rules_pkg#626]
Pretty much what the title says. The [`package_dir`](https://github.com/bazelbuild/rules_pkg/blob/4891d9fe6c32c4e26ad4766261fde13ae684bbb2/pkg/private/tar/tar.bzl#L78-L86) attribute becomes `self.directory` in [`build_tar.py`](https://github.com/bazelbuild/rules_pkg/blob/4891d9fe6c32c4e26ad4766261fde13ae684bbb2/pkg/private/tar/build_tar.py#L49), but it is not taken into account when archiving symlinks (and pretty much anything that is not a file, see [`normpath`](https://github.com/bazelbuild/rules_pkg/blob/4891d9fe6c32c4e26ad4766261fde13ae684bbb2/pkg/private/tar/build_tar.py#L29-L37) vs [`Tarfile.normalize_path`](https://github.com/bazelbuild/rules_pkg/blob/4891d9fe6c32c4e26ad4766261fde13ae684bbb2/pkg/private/tar/build_tar.py#L66-L76)). Is this intentional?

**Comment by aiuto** [comment]
Can you provide a reproduction highlighting the issue.

**Comment by pauldraper** [comment]
Fixed by 637. 🎉

**Comment by pauldraper** [comment]
Fixed by #637. 🎉
