### ISSUE TITLE
`pkg_deb` file spec seems to be corrupted in `.changes` file

### ISSUE THREAD

**Issue by phlax** [bazelbuild/rules_pkg#632]
Attempting to upgrade to 0.7.1 our deb publishing pipeline fails unable to use `dscverify` to check the signatures on the debs/changes

On further investigation - this is what changed:

```dsc

Files: 
 104017c7c884bc833a3c46d044295f51 99165210 contrib/devel optional envoy_1.25.0-dev_amd64.deb

```

->

```dsc
Files: ad524b04821992a3037b2ef26c55f8f2 99165210 contrib/devel optional envoy_1.25.0-dev_amd64.deb
```

Checking the spec - it seems like this is not allowed - https://www.debian.org/doc/debian-policy/ch-controlfields.html#files

certainly it causes `dscverify` to fail with:

```console

# dscverify --keyring /usr/share/debsign/keyring.gpg /tmp/install/deb/envoy_1.25.0-dev_amd64.bullseye.changes 
/tmp/install/deb/envoy_1.25.0-dev_amd64.bullseye.changes:
      Good signature found
dscverify: no file spec lines in /tmp/install/deb/envoy_1.25.0-dev_amd64.bullseye.changes
Validation FAILED!!

```

**Comment by aiuto** [comment]
That was probably introduced by the cleanup to handling multiline fields like Description.
TBH, I'm not going to look at anything in rules_pkg until December at the earliest.
Happy to take a PR. My hunch is that we want a different variant or option to MakeDebianControlField
that simply takes a list of values and emits them joined with '\n '.

It would also be great to have deb verification tests that work on CI.
