### ISSUE TITLE
Bump latest version to 0.8.0 in readme

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_pkg#634]
Landing page says:

> Latest version: 0.7.0 [Release Notes](https://github.com/bazelbuild/rules_pkg/releases/tag/0.7.0) (with WORKSPACE setup) / [Documentation](https://bazelbuild.github.io/rules_pkg/0.7.0/reference.html)

Seems like an oversight but maybe I'm missing a piece of the workflow. 0.8.0 was released a couple days ago.

**Comment by aiuto** [comment]
Forever fixed in [e5d2ca0](https://github.com/bazelbuild/rules_pkg/commit/e5d2ca093751a6e93a1af3bec88037042d293a70) by just pointing to the releases page.
