### ISSUE TITLE
rules_deb produces invalid Files- and Checksum-sections

### ISSUE THREAD

**Issue by msiebuhr** [bazelbuild/rules_pkg#659]
Per https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-files, `Files` (and Checksum-XX)-sections must  have the first line empty, ex:

```
Files:
 c6f698f19f2a2aa07dbb9bbda90a2754 571925 example_1.2.orig.tar.gz
```

Yet `rules_deb` produces:

```
Files: c6f698f19f2a2aa07dbb9bbda90a2754 571925 example_1.2.orig.tar.gz
```

The relevant code _does_ try to do the right thing when generating the fields

https://github.com/bazelbuild/rules_pkg/blob/547077f0b1d3f60a325429a9b4c6de965ab2f3b4/pkg/private/deb/make_deb.py#L299-L307

But `MakeDebianControlField()` promptly strips it away

 https://github.com/bazelbuild/rules_pkg/blob/547077f0b1d3f60a325429a9b4c6de965ab2f3b4/pkg/private/deb/make_deb.py#L134-L138

A trivial fix could be to write out `Files:\n  " + " ".join([...])` and skip calling `MakeDebianControlField()`?

**Comment by msiebuhr** [comment]
For now, I have hacked around it by piping my .changes-file through `sed -E 's/(Files|Checksums-.*): /\1:\n  /'`.

**Comment by aiuto** [comment]
Might be the same as #632

**Comment by phlax** [comment]
looks same to me
