### ISSUE TITLE
Provide a tool that can verify certain files are (or not) in an archive

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_pkg#666]
Some people insist on doing tests against a golden file to make sure all the expected files are in an archive.
This is both painful to update and brittle w.r.t. ordering changes.

We should provide a tool that let's people do these structural tests in a way that is less brittle.

**Comment by mnil** [comment]
How is this issue different from https://github.com/bazelbuild/rules_pkg/issues/644?

**Comment by aiuto** [comment]
<slaps head>
Yup. This is dup of that.
