### ISSUE TITLE
Wrong release description for release 0.9.0

### ISSUE THREAD

**Issue by martis42** [bazelbuild/rules_pkg#694]
The checksum for `rules_pkg-0.9.0.tar.gz` in the WORKSPACE snippet for https://github.com/bazelbuild/rules_pkg/releases/tag/0.9.0 is wrong.
The checksum is actually `bcc96ae58d9d61db1a36a13d29e85dc2c1696ecb7997f9a26643ab0971ecb2ef`

**Comment by aiuto** [comment]
That's odd.  The mirror is correct, (335632735e625d408870ec3e361e192e99ef7462315caa887417f4d88c4c8fb8) but the github served version is not.
I also found the original from the machine I built the release on. That matches the mirror.

I did some examination of the two versions and the mirror one is right. I'll update the release.

**Comment by sanitybit** [comment]
What were the difference between the mirror version and the GitHub served version? Does anyone have an archive I can compare?

**Comment by aiuto** [comment]
The workspace.resolved and some other unused file got included in the bad version.
There were no behavioral changes.

**Comment by davidr-bt** [comment]
Builds still fail with checksum mismatch error.

**Comment by martis42** [comment]
Restoring the old version of the artifact might fix downstream projects which already depend on the initial release behavior, but it can't fix the release.
If the old version is restored, then there are again 2 non matching artifacts depending on downlaoding either via the mirror or the Github URL (plus the description only matchign one).

Seems to me the only forward path is a new release and hoping all downstream users update to it.

**Comment by alexeagle** [comment]
the mirror.bazel.build has to be fixed to have an artifact with sha256 `bcc96ae58d9d61db1a36a13d29e85dc2c1696ecb7997f9a26643ab0971ecb2ef`

A new release is also a good idea, but you'll have endless reports of this breakage since the original artifact was live for nearly two months before being replaced.

**Comment by aiuto** [comment]
I'll yank 0.9.0 and do a 0.9.1.  Most likely on Tuesday, May 2

**Comment by meteorcloudy** [comment]
Re-open until this is resolved properly.

**Comment by aiuto** [comment]
I made a 0.9.1 and sent a PR to update BCR.

FWIW. I spent some time trying to use `gh` to script the update. I was close, but ran into authentication headaches, as releases pushes are done from a remote, headless machine, so browser authentication is tricky.  I'll come back to that some time later in the quarter.

**Comment by aiuto** [comment]
But the question of yanking 0.9.0 is open. 
It seems no-worse to yank than leave as is, because people who explicitly ask for 0.9.0 are failing anyway.

**Comment by aiuto** [comment]
Waiting on https://github.com/bazelbuild/bazel-central-registry/pull/605
