### ISSUE TITLE
Add changelog attribute to pkg_deb rule

### ISSUE THREAD

**Issue by k0walik** [bazelbuild/rules_pkg#696]
I noticed the `pkg_deb` rule does not provide `changelog` input attribute, while `pkg_rpm` does. Is it intended behavior? My use case assumes creating DEB and RPM packages, where the changelog is automatically generated and forwarded to package generation rules.

While looking at the rule implementation it seems to be trivial task.

**Comment by aiuto** [comment]
Not intended. It's just that no one ever bothered to add it.
