### ISSUE TITLE
check_certs test in deb_packages_base example fails on osx

### ISSUE THREAD

**Issue by mrinalwadhwa** [bazelbuild/rules_pkg#7]
This test fails when developing on macOS.
https://github.com/bazelbuild/rules_pkg/blob/master/examples/deb_packages/deb_packages_base/BUILD#L170-L174

I suspect this is because the `check_certs` binary was compiled on macOS but is being invoked inside debian. There is probably a way to cross compile.

**Comment by mrinalwadhwa** [comment]
asked the questions here
https://github.com/bazelbuild/rules_go/issues/1009#issuecomment-360016948

**Comment by aiuto** [comment]
Examples need dusting before anyone can look at this #181 is a start, but that's all I have time for.

**Comment by aiuto** [comment]
Closing as obsolete. The docker building rules have forked to https://github.com/aisbaa/deb_packages. #259
