### ISSUE TITLE
No docs for 0.9 versions

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_pkg#716]
https://github.com/bazelbuild/rules_pkg/blob/main/docs/latest.md documents 0.8.2

Is this a manual process on releases?

**Comment by aiuto** [comment]
It's manual. I have not found the time payoff in automating it robustly.

Doing 'latest' is easy, or not, depending on what we consider latest to mean.
I've been treating it as head, but the issue description might imply you take it to mean latest release. 

The versioned releases are their own question. I don't think having a distinct text for every release adds value. It encourages web search to find obsolete docs. OTOH, some people do want the docs for the specific thing they are using.

Anyway, #739 and #740 are out to do some updates.

**Comment by alexeagle** [comment]
I'd like to fix this permanently to reduce the maintenance burden in this repo. I have the time to automate it robustly.

https://github.com/bazel-contrib/rules-template/tree/main/docs is the pattern used in a dozen rulesets. It's just a regular test that asserts the markdown at HEAD always matches the stardoc output at HEAD. Every PR updates the docs.
Users can use the GitHub UI to read docs at any tag they choose.

Can I send you a PR for this, rather than a special effort for 0.9? I think we should cut releases regularly, but the more effort required, the less likely we are to find the time to perform them.

**Comment by aiuto** [comment]
How does this account for the post processing pipeline that assembles the
unified doc set and fixes the bad stardoc generation.

**Comment by alexeagle** [comment]
There's no post-processing. We can make a unified experience with a table of contents like https://github.com/aspect-build/bazel-lib#public-api
and for bad stardoc generation, I either fix that upstream or use a fork of stardoc with some of my fixes.

Would you like a PR to see what this will look like?

**Comment by aiuto** [comment]
I'm not going to fork stardoc. I will keep nudging them to fix it instead.
How about if the update rule from the template were modified to take two
parameters
- the target which generates the doc file(s)
- the page(s) to place them at.

That would incorporate any doc generation scheme, stardoc or not.

**Comment by alexeagle** [comment]
Can you point to the stardoc bug? I wonder if it's the dedenting issue that caused me to fork but was recently fixed.

**Comment by aiuto** [comment]
https://github.com/bazelbuild/stardoc/issues/120
https://github.com/bazelbuild/stardoc/issues/118
https://github.com/bazelbuild/stardoc/issues/98s

There are probably others. 
I'm not sure if the stardoc rule lets me control the order of methods declared, or if it would sort them alphabetically (that would be a new bug).

The non-generated text that I need could be put in the silverlight template.

**Comment by alexeagle** [comment]
There are docs for 0.9 now, so this is solved as reported. I get the sense that you're not really interested in automating the docs process and don't want to make a big deal out of it.

**Comment by aiuto** [comment]
There is some push from internal security teams to redo the release process
in specific ways.  I'm in negotiation with them about their requests

**Comment by alexeagle** [comment]
Could I get a contact info from someone there? I'd like to get the Bazel-contrib rules-template that all the community rules are based on

**Comment by aiuto** [comment]
+Tobias Werth ***@***.***>
The best contact for Bazel policy is Tobi, or myself if strictly about
rules_license or rules_pkg.

**Comment by alexeagle** [comment]
Probably better to take this to a dedicated issue: https://github.com/bazel-contrib/rules-template/issues/99
