### ISSUE TITLE
The files map in pkg_tar is the wrong way around

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_pkg#753]
Currently, `pkg_tar` works with the keys as the source-files and the values as the paths in the tar:

```starlark
pkg_tar(
  name = "jq_1_7_linux_amd_64",
  strip_prefix = "",
  files = {
    "@jq_1_7_linux_amd_64//file": "/usr/bin/jq",
  },
)
```

However, this makes little sense, since the file path must be unique, but plausibly the same input could be included twice.

The key-value semantics should be flipped:

```starlark
pkg_tar(
  name = "jq_1_7_linux_amd_64",
  strip_prefix = "",
  files = {
    "/usr/bin/jq": "@jq_1_7_linux_amd_64//file",
    "/usr/bin/jq17": "@jq_1_7_linux_amd_64//file",
  },
)
```

**Comment by aiuto** [comment]
`files` is a deprecated feature. It's insufficient for so many cases and only works with tar. You could use 2 `pkg_files` targets to take the same input and put it in to distinct output paths, then have those as input to the `pkg_tar` target.

**Comment by aiuto** [comment]
Closing because there is no way to change this silly behavior without breaking everyone who uses it and there are other ways to accomplish the desired effect.
