### ISSUE TITLE
Add support for XZ

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/rules_pkg#76]
As part of https://github.com/bazelbuild/rules_docker/issues/1083 we need to add support for xz compression to build_tar.py
Specific PRs (from rules_docker) which capture the needed functionality are:
https://github.com/bazelbuild/rules_docker/pull/433 - added feature
https://github.com/bazelbuild/rules_docker/pull/473 - support for lzma
https://github.com/bazelbuild/rules_docker/pull/636 - toolchains for xz

rules_docker owners will take care of sending PRs to this repo to add feature, likely in early Q4 2019.

**Comment by nlopezgi** [comment]
(please assign this issue to me if possible as I cant assign)

**Comment by aiuto** [comment]
FWIW. I am willing to require a Python3 toolchain for packaging rules. That would simplify the fallback code for lzma.

**Comment by nlopezgi** [comment]
Thanks for the suggestion. We'll let you know once were ready to start work on this to sync about implementation options.

**Comment by aiuto** [comment]
This might be obsolete.   We have switched to Python3 for the tar rules and .xz seems to be working on mac and linux.
