### ISSUE TITLE
Produce Debian status file

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/rules_pkg#77]
As part of bazelbuild/rules_docker#1083 we need to add support for xz compression to build_tar.py
Specific PR (from rules_docker) which capture the needed functionality is:
https://github.com/bazelbuild/rules_docker/pull/239 - generate per package metadata file

rules_docker owners will take care of sending PRs to this repo to add feature, likely in early Q4 2019.
(please assign this issue to me if possible as I cant assign)

**Comment by aiuto** [comment]
I'm closing this for now.  We can open a new one with a clearer request.
