### ISSUE TITLE
Deprecation Warning in `build_zip.py` `datetime.datetime.utcfromtimestamp()` is deprecated and scheduled for removal in a future version

### ISSUE THREAD

**Issue by guw** [bazelbuild/rules_pkg#826]
I started to see this on MacOS Sonoma 14.3.1:

```
INFO: From PackageZip ...:
.../external/rules_pkg/pkg/private/zip/build_zip.runfiles/core/../rules_pkg/pkg/private/zip/build_zip.py:77: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  ts = datetime.datetime.utcfromtimestamp(ts)
```

Might be related to a recent `brew upgrade`?

**Comment by aiuto** [comment]
A newer Python must have deprecated it.  This should be easy to fix. The only constraint is that we don't pick an API which is only in the most recent Pythons.

**Comment by pauldraper** [comment]
Yes, this is deprecated in Python 3.12.

> [datetime](https://docs.python.org/3/library/datetime.html#module-datetime): [datetime.datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime)’s [utcnow()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) and [utcfromtimestamp()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp) are deprecated and will be removed in a future version. Instead, use timezone-aware objects to represent datetimes in UTC: respectively, call [now()](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) and [fromtimestamp()](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) with the tz parameter set to [datetime.UTC](https://docs.python.org/3/library/datetime.html#datetime.UTC).

Fortunately, datetime.fromtimestamp has been available ~forever.

**Comment by aiuto** [comment]
SGTM. fix on the way
