### ISSUE TITLE
File owners are losed when pkg_tar merged into other pkg_tar via `deps` attribute

### ISSUE THREAD

**Issue by ppodolsky** [bazelbuild/rules_pkg#83]
`pkg_tar` with files owned by a particular owner loses this information if is used in other `pkg_tar` as dependency.
Erasing of owners occurs [here](https://github.com/bazelbuild/rules_pkg/blob/master/pkg/archive.py#L388)
What is the reason of the existence of this `numeric` argument?

**Comment by aiuto** [comment]
Can you provide an example of this? Are you trying to unroll the first tar file and include its content as individual files in the second?

**Comment by ppodolsky** [comment]
Here it is
```
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar", "pkg_deb")

pkg_tar(
    name = "dep1",
    srcs = [":test.txt"],
    ownername = "ololo.ololo"
)

pkg_tar(
    name = "dep2",
    deps = [
        ":dep1",
    ],
)
```
then build
```
pasha$ bazel build :dep2
pasha$ tar tvf ../bazel-bin/dep1.tar
drwxr-xr-x  0 ololo  ololo       0 Jan  1  2000 ./
-r-xr-xr-x  0 ololo  ololo       6 Jan  1  2000 ./test.txt
pasha$ tar tvf ../bazel-bin/dep2.tar
drwxr-xr-x  0 0      0           0 Jan  1  2000 ./
-r-xr-xr-x  0 0      0           6 Jan  1  2000 ./test.txt
```

**Comment by aiuto** [comment]
I'm going to argue that the behavior we have is entirely wrong.  The content of dep2.tar should not be test.txt. It should be  ./dep1.tar.

**Comment by ppodolsky** [comment]
Would like to argue too. You can get this behavior by placing ‘:deps1’ dependency into ‘srcs’ parameter of ‘:deps2’. 
Otherwise what is a way to construct complex tars with different paths?

**Comment by aiuto** [comment]
We have two issues here.

1. The owner information should be preserved. If it was numeric, the numeric should be preserved. If it was textual, the textual names should be preserved.  That leads to secondary concerns:
- mixing text and numeric in the same package should be an error. It is sloppy packaging and not clear how a user would interpret it.
- we would need an option to specify the that we want numeric or text uids used in the package.
- Should the packaging tar rule be able to change the owners of the original files? Of course yes. That is a valid use case where you want to sanitize an input tarball which might be checked in. That becomes yet another option.

2. Should we be able to repackage tars like this? I think the current behavior is a terrible hack. A disciplined solution would allow you to control if you want it untarted and retarred in, or if you want to include it intact as a blob.  The better solution should apply to all packaging rules. For example, it should be trivial to repackage a .tar file as a .zip, without writing a genrule to expand zip and then tar it.

**Comment by ashi009** [comment]
> 2. Should we be able to repackage tars like this? I think the current behavior is a terrible hack. A disciplined solution would allow you to control if you want it untarted and retarred in, or if you want to include it intact as a blob.  The better solution should apply to all packaging rules. For example, it should be trivial to repackage a .tar file as a .zip, without writing a genrule to expand zip and then tar it.

If we want the tar inside, it should be placed in srcs.

**Comment by aiuto** [comment]
I am folding this in to #355.  We should fix this with pkg_expand, so it works for pkg_zip too, rather than just for pkg_tar.

**Comment by aiuto** [comment]
I am folding this in to #355.  We should fix this with pkg_expand, so it works for pkg_zip too, rather than just for pkg_tar.
