### ISSUE TITLE
pkg_tar with include_runfiles won't accept a directory as a src

### ISSUE THREAD

**Issue by ss185994** [bazelbuild/rules_pkg#835]
As the title says when I try to `include_runfiles` in `pkg_tar` while passing a directory as a `src` I get the error `IsADirectoryError: [Errno 21] Is a directory: 'bazel-out/k8-fastbuild/bin/src/bundle'`

I made a sample repo https://github.com/ss185994/pkg_thing/tree/main 

Is there a recommended flow for doing this?

**Comment by dieortin** [comment]
This should be solved by #830

**Comment by ss185994** [comment]
@dieortin dang it Im blind thanks for the quick link

**Comment by aiuto** [comment]
closing as duplicate
