### ISSUE TITLE
pkg_zip drops execute attribute when zipping executable file

### ISSUE THREAD

**Issue by statik** [bazelbuild/rules_pkg#96]
I am using `pkg_zip` to zip up a `go_binary` generated using bazel_rules_go. The go_binary has the execute bit set, but when I unpack the contents of the generated zip file, the program does not have the execute bit set.

The goal I'm trying to accomplish is to deliver an artifact that can run in AWS Lambda, and the lambda environment is expecting the execute bit to be set.

I'm happy to try and contribute a fix for this, figured opening an issue was a good first step.

**Comment by j3parker** [comment]
Ouch, that's unfortunate.

It looks like [ZipInfo.external_attrs](https://docs.python.org/3/library/zipfile.html#zipfile.ZipInfo.external_attr) might be the ticket. See [4.4.2 and 4.4.15 of this document](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT), maybe, for some more details.

**Comment by j3parker** [comment]
Ah you beat me to it :) Thanks.

**Comment by aiuto** [comment]
Solutions that look at the file system mode (like https://github.com/kindlyops/rules_pkg/commit/4a8c3e79f6cc83c10bab6357bfcce6be695d925e) do not work in general for Bazel, especially when remote build and caching are involved.  

Modes we want in the .tar (or .zip, .rpm, .msi, ...) have to be specified in BUILD files in some way.
Have you tried a **mode** attribute in your BUILD rules?

**Comment by statik** [comment]
Thanks! I will give adding a mode attribute a try. 

Note that pkg_tar attempts to look at the mode of the source file as well, I wonder if that is a bug? https://github.com/bazelbuild/rules_pkg/blob/b8d6ea0a5465973ce0970f6e063dfebea473732c/pkg/build_tar.py#L69-L71

**Comment by statik** [comment]
I've redone #97 to use a mode attribute in the BUILD rule as suggested, it seems to work well. Thanks!

**Comment by scorsi** [comment]
Hope it's resolved I'm facing some trouble while migrating to Bazel build. :)

**Comment by statik** [comment]
Hi @scorsi sorry you are hitting this. I don't know why #97 hasn't been merged yet. I've had to stop using rules_pkg because of this and #104.

As an alternative, this genrule works for zipping up a binary to deploy to AWS lambda
```
genrule(
    name = "lambda_deploy",
    srcs = [":lambda_binary"],
    outs = ["lambda_deploy.zip"],
    cmd = "$(location @bazel_tools//tools/zip:zipper) c $@ main=$(SRCS)",
    tools = ["@bazel_tools//tools/zip:zipper"],
    visibility = ["//visibility:public"],
)
```

**Comment by scorsi** [comment]
@statik It locks like this zip rule is completely broken haha :) 
Thanks for the tip, I will investigate it.

**Comment by scorsi** [comment]
Thanks @statik, it works fine with the `genrule` + `zipper` ! 🚀

**Comment by aiuto** [comment]
I think I can now address this in a reasonable way, and it will tie together with support for adding runfiles.
The implementation I am thinking of is to move normal file processing into pkg_files.process_src
It can do the DefaultInfo processing to support all pkg_types at once.
I think the only problem is that pkg_tar won't be able to make use of that if you want to use the `files` attribute to remap files.  That's not really a problem. You can do the remap with pkg_files if you want the runfiles support.
pkg_zip will work without problem, because it didn't add the weird crap in pkg_tar.

**Comment by aiuto** [comment]
Do you have a reproduction?  This says fixed from 9 moths ago?
