### ISSUE TITLE
Bazel website documentation

### ISSUE THREAD

**Issue by quentingodeau** [bazelbuild/rules_pkg#98]
Hi everyone, I not sure that I'm posting to the right place...

I was wondering where the documentation goes.
Before this repository moved there where only one Bazel website with the doc. Now it's tag as deprecated but there is no new link to another website.
So my issue is in fact maybe two:
- where can I find the pkg_rules documentation/example ?
- is there a plan to re-put all the documentation/example under the same website ?

Thanks in advance.

**Comment by aiuto** [comment]
> Where can I find the pkg_rules documentation/example ? In the source.  https://github.com/bazelbuild/rules_pkg/tree/master/pkg

> is there a plan to re-put all the documentation/example under the same website ?
Not at this time. There might be a central index, but we would have to figure out how to nicely cope with the fact that every rule set has their own release cycle. That is a problem for bazelbuild/bazel, rather than this site.
